# generated_fitness_zero_shot.py
# Generated by generate_fitness_zero_shot.py
# One-function-at-a-time zero-shot LLM fitness generation.

GENERATED_TARGETS = {
    'number_kind': ['zero', 'even', 'odd'],
    'sign_type': ['positive', 'negative', 'zero'],
    'string_category': ['empty', 'long_palindrome', 'short_palindrome', 'long_non_palindrome', 'other'],
}

GENERATED_INPUT_SCHEMAS = {
    'number_kind': [{'type': 'int', 'min': -500.0, 'max': 3000.0}],
    'sign_type': [{'type': 'int', 'min': -500.0, 'max': 3000.0}],
    'string_category': [{'type': 'str', 'min_len': 0, 'max_len': 15}],
}

# ================================================================================
# Original function: number_kind
# Fitness function: fitness_number_kind
# LLM targets: ['zero', 'even', 'odd']
# Notes: Fitness function for number_kind with branch distance.
# ================================================================================

TARGETS_number_kind = ["zero", "even", "odd"]

def fitness_number_kind(chromosome, target):
    if target not in TARGETS_number_kind:
        raise ValueError("Unknown target: {}".format(target))
    x = chromosome[0]
    if target == "zero":
        distance = abs(x)
    elif target == "even":
        if x == 0:
            distance = 1
        elif x % 2 == 0:
            distance = 0
        else:
            distance = 1
    elif target == "odd":
        if x == 0:
            distance = 1
        elif x % 2 == 1:
            distance = 0
        else:
            distance = 1
    else:
        distance = 1
    return max(0, distance)

# ================================================================================
# Original function: sign_type
# Fitness function: fitness_sign_type
# LLM targets: ['positive', 'negative', 'zero']
# Notes: 
# ================================================================================

TARGETS_sign_type = ["positive", "negative", "zero"]

def fitness_sign_type(chromosome, target):
    if target not in TARGETS_sign_type:
        raise ValueError("Unknown target")
    x = chromosome[0]
    if target == "positive":
        if x > 0:
            return 0
        else:
            return max(0, -x) + 1
    elif target == "negative":
        if x < 0:
            return 0
        else:
            return max(0, x) + 1
    elif target == "zero":
        if x == 0:
            return 0
        else:
            return abs(x) + 1

# ================================================================================
# Original function: string_category
# Fitness function: fitness_string_category
# LLM targets: ['empty', 'long_palindrome', 'short_palindrome', 'long_non_palindrome', 'other']
# Notes: Fitness function returns 0 only when the chromosome would produce the specified target label; otherwise it returns 1.
# ================================================================================

TARGETS_string_category = [
    "empty",
    "long_palindrome",
    "short_palindrome",
    "long_non_palindrome",
    "other"
]


def fitness_string_category(chromosome, target):
    if target not in TARGETS_string_category:
        raise ValueError("Unknown target")
    s = chromosome[0]
    if len(s) == 0:
        actual = "empty"
    elif s == s[::-1] and len(s) > 3:
        actual = "long_palindrome"
    elif s == s[::-1]:
        actual = "short_palindrome"
    elif len(s) > 5:
        actual = "long_non_palindrome"
    else:
        actual = "other"
    if actual == target:
        return 0
    else:
        return 1

# ================================================================================
# Unified fitness interface
# ================================================================================

def evaluate_fitness(function_name, chromosome, target):
    if function_name == 'number_kind':
        return fitness_number_kind(chromosome, target)
    elif function_name == 'sign_type':
        return fitness_sign_type(chromosome, target)
    elif function_name == 'string_category':
        return fitness_string_category(chromosome, target)
    else:
        raise ValueError(f'Unknown function name: {function_name}')
