# generated_fitness_no_semantic_openai_gpt_oss_120b.py
# Generated by generate_fitness_zero_shot.py
# Provider: groq
# Model: openai/gpt-oss-120b
# Fitness version: without_semantic_validation
# One-function-at-a-time LLM fitness generation.

GENERATED_TARGETS = {
    'bmi_category': ['invalid_height', 'underweight', 'normal', 'overweight', 'obese'],
    'list_pattern': ['too_short', 'sorted_unique', 'sorted_with_duplicates', 'unsorted_unique', 'unsorted_with_duplicates'],
    'number_kind': ['zero', 'even', 'odd'],
    'password_strength': ['weak_short', 'strong', 'medium', 'weak_no_digit_upper'],
    'pin_pattern': ['secret_pin', 'all_same', 'ordered_sum_20', 'other'],
    'shipping_discount': ['invalid', 'free_express_shipping', 'standard_discount', 'small_discount', 'no_discount'],
    'sign_type': ['positive', 'negative', 'zero'],
    'string_category': ['empty', 'long_palindrome', 'short_palindrome', 'long_non_palindrome', 'other'],
    'transaction_pattern': ['empty', 'contains_zero', 'many_large_deposits', 'many_large_withdrawals', 'mixed_transactions', 'simple_pattern'],
    'triangle_type': ['invalid_side', 'not_triangle', 'equilateral', 'isosceles', 'scalene'],
    'username_category': ['empty', 'too_short', 'starts_with_digit', 'strong_username', 'medium_username', 'weak_username'],
}

GENERATED_INPUT_SCHEMAS = {
    'bmi_category': [{'type': 'float', 'min': 0.0, 'max': 3000.0}, {'type': 'float', 'min': 0.0, 'max': 3000.0}],
    'list_pattern': [{'type': 'list_int', 'min': -100.0, 'max': 100.0, 'min_len': 0, 'max_len': 6}],
    'number_kind': [{'type': 'int', 'min': -500.0, 'max': 3000.0}],
    'password_strength': [{'type': 'str', 'min_len': 0, 'max_len': 15}],
    'pin_pattern': [{'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'int', 'min': -500.0, 'max': 3000.0}],
    'shipping_discount': [{'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'bool'}],
    'sign_type': [{'type': 'int', 'min': -500.0, 'max': 3000.0}],
    'string_category': [{'type': 'str', 'min_len': 0, 'max_len': 15}],
    'transaction_pattern': [{'type': 'list_int', 'min': -100.0, 'max': 100.0, 'min_len': 0, 'max_len': 6}],
    'triangle_type': [{'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'int', 'min': -500.0, 'max': 3000.0}],
    'username_category': [{'type': 'str', 'min_len': 0, 'max_len': 15}],
}

# ================================================================================
# Original function: bmi_category
# Fitness function: fitness_bmi_category
# LLM targets: ['invalid_height', 'underweight', 'normal', 'overweight', 'obese']
# Notes: Fitness returns 0 exactly when the original function would return the specified label; otherwise a non‑negative branch‑distance value is provided.
# ================================================================================

def fitness_bmi_category(chromosome, target):
    weight = chromosome[0]
    height = chromosome[1]
    # distance for height condition (height must be <= 0 for invalid_height, >0 otherwise)
    height_dist = max(0.0, height)
    if height <= 0:
        label = "invalid_height"
        dist = height_dist
    else:
        bmi = weight / (height * height)
        # determine actual label
        if bmi < 18.5:
            label = "underweight"
        elif bmi < 25:
            label = "normal"
        elif bmi < 30:
            label = "overweight"
        else:
            label = "obese"
        # compute branch distance for the requested target
        if target == "underweight":
            dist = max(0.0, bmi - 18.5)
        elif target == "normal":
            if bmi < 18.5:
                dist = 18.5 - bmi
            elif bmi >= 25:
                dist = bmi - 25
            else:
                dist = 0.0
        elif target == "overweight":
            if bmi < 25:
                dist = 25 - bmi
            elif bmi >= 30:
                dist = bmi - 30
            else:
                dist = 0.0
        elif target == "obese":
            dist = max(0.0, 30 - bmi)
        elif target == "invalid_height":
            dist = height_dist
        else:
            raise ValueError(f"Unknown target: {target}")
        # height must be >0 for all non‑invalid targets
        if target != "invalid_height":
            dist = dist + height_dist
    # fitness value: 0 only when the target matches the actual label
    if target == label:
        return 0.0
    else:
        return max(0.0, dist)

# ================================================================================
# Original function: list_pattern
# Fitness function: fitness_list_pattern
# LLM targets: ['too_short', 'sorted_unique', 'sorted_with_duplicates', 'unsorted_unique', 'unsorted_with_duplicates']
# Notes: The fitness function computes branch‑distance‑like values for each possible return label of list_pattern without invoking the original function. All distances are non‑negative and become zero exactly when the chromosome would cause the original function to return the selected target.
# ================================================================================

def fitness_list_pattern(chromosome, target):
    nums = chromosome[0]
    len_n = len(nums)
    len_dist = max(0, 2 - len_n)
    # sorted distance: count of adjacent inversions
    sorted_dist = 0
    for i in range(len_n - 1):
        if nums[i] > nums[i + 1]:
            sorted_dist += 1
    dup_dist = len_n - len(set(nums))
    unsorted_cond = max(0, 1 - sorted_dist)
    duplicate_present = max(0, 1 - dup_dist)
    if target == "too_short":
        return len_dist
    elif target == "sorted_unique":
        return len_dist + sorted_dist + dup_dist
    elif target == "sorted_with_duplicates":
        return len_dist + sorted_dist + duplicate_present
    elif target == "unsorted_unique":
        return len_dist + unsorted_cond + dup_dist
    elif target == "unsorted_with_duplicates":
        return len_dist + unsorted_cond + duplicate_present
    else:
        raise ValueError("Unknown target: " + str(target))

# ================================================================================
# Original function: number_kind
# Fitness function: fitness_number_kind
# LLM targets: ['zero', 'even', 'odd']
# Notes: Fitness returns 0 only when the original function would return the corresponding label.
# ================================================================================

def fitness_number_kind(chromosome, target):
    x = chromosome[0]
    if target == "zero":
        return 0 if x == 0 else max(0, abs(x))
    elif target == "even":
        return 0 if (x != 0 and x % 2 == 0) else 1
    elif target == "odd":
        return 0 if (x % 2 != 0) else 1
    else:
        raise ValueError("Unknown target: {}".format(target))

# ================================================================================
# Original function: password_strength
# Fitness function: fitness_password_strength
# LLM targets: ['weak_short', 'strong', 'medium', 'weak_no_digit_upper']
# Notes: 
# ================================================================================

def fitness_password_strength(chromosome, target):
    s = chromosome[0]
    length = len(s)
    has_digit = any(ch.isdigit() for ch in s)
    has_upper = any(ch.isupper() for ch in s)

    if target == "weak_short":
        dist = max(0, length - 5)
        return dist
    elif target == "strong":
        dist_len = max(0, 10 - length)
        dist_digit = 0 if has_digit else 1
        dist_upper = 0 if has_upper else 1
        return dist_len + dist_digit + dist_upper
    elif target == "medium":
        dist_len_min = max(0, 6 - length)
        dist_digit_upper = 0 if (has_digit or has_upper) else 1
        strong_cond = (length >= 10) and has_digit and has_upper
        dist_not_strong = 0 if not strong_cond else 1
        return dist_len_min + dist_digit_upper + dist_not_strong
    elif target == "weak_no_digit_upper":
        dist_len_min = max(0, 6 - length)
        dist_digit = 0 if not has_digit else 1
        dist_upper = 0 if not has_upper else 1
        return dist_len_min + dist_digit + dist_upper
    else:
        raise ValueError("Unknown target: " + str(target))

# ================================================================================
# Original function: pin_pattern
# Fitness function: fitness_pin_pattern
# LLM targets: ['secret_pin', 'all_same', 'ordered_sum_20', 'other']
# Notes: The fitness function computes a non‑negative branch‑distance for each possible return label of pin_pattern. It returns 0 exactly when the chromosome would cause the original function to return the selected target.
# ================================================================================

TARGETS_pin_pattern = ["secret_pin", "all_same", "ordered_sum_20", "other"]

def fitness_pin_pattern(chromosome, target):
    a, b, c, d = chromosome
    # distance to secret_pin condition
    dist_secret = max(0, abs(a - 7) + abs(b - 3) + abs(c - 9) + abs(d - 1))
    # distance to all_same condition
    diff_ab = abs(a - b)
    diff_ac = abs(a - c)
    diff_ad = abs(a - d)
    dist_all_same = max(diff_ab, diff_ac, diff_ad)
    # distance to ordered_sum_20 condition
    sum_dist = abs((a + b + c + d) - 20)
    order_dist = 0
    if a >= b:
        order_dist += (a - b + 1)
    if b >= c:
        order_dist += (b - c + 1)
    if c >= d:
        order_dist += (c - d + 1)
    dist_ordered = sum_dist + order_dist
    # distance to other condition (true when none of the above are satisfied)
    other_condition = (dist_secret == 0) or (dist_all_same == 0) or (dist_ordered == 0)
    dist_other = 1 if other_condition else 0
    if target == "secret_pin":
        return dist_secret
    elif target == "all_same":
        return dist_all_same
    elif target == "ordered_sum_20":
        return dist_ordered
    elif target == "other":
        return dist_other
    else:
        raise ValueError("Unknown target: " + str(target))

# ================================================================================
# Original function: shipping_discount
# Fitness function: fitness_shipping_discount
# LLM targets: ['invalid', 'free_express_shipping', 'standard_discount', 'small_discount', 'no_discount']
# Notes: Fitness function returns 0 exactly when the original shipping_discount would return the specified label; otherwise returns a positive branch‑distance value.
# ================================================================================

TARGETS_shipping_discount = [
    "invalid",
    "free_express_shipping",
    "standard_discount",
    "small_discount",
    "no_discount"
]

def fitness_shipping_discount(chromosome, target):
    order_total = chromosome[0]
    distance = chromosome[1]
    is_member = chromosome[2]

    if target == "invalid":
        cond = (order_total < 0) or (distance < 0)
        if cond:
            return 0
        d1 = max(0, order_total)
        d2 = max(0, distance)
        return max(0, d1 + d2)

    if target == "free_express_shipping":
        cond = (order_total >= 200) and (distance <= 50) and is_member
        if cond:
            return 0
        d1 = max(0, 200 - order_total)
        d2 = max(0, distance - 50)
        d3 = 0 if is_member else 1
        return max(0, d1 + d2 + d3)

    if target == "standard_discount":
        earlier_invalid = (order_total < 0) or (distance < 0)
        earlier_free = (order_total >= 200) and (distance <= 50) and is_member
        cond = (order_total >= 100) and (distance <= 100) and not earlier_invalid and not earlier_free
        if cond:
            return 0
        d1 = max(0, 100 - order_total)
        d2 = max(0, distance - 100)
        penalty = 1 if earlier_invalid or earlier_free else 0
        return max(0, d1 + d2 + penalty)

    if target == "small_discount":
        earlier_invalid = (order_total < 0) or (distance < 0)
        earlier_free = (order_total >= 200) and (distance <= 50) and is_member
        earlier_std = (order_total >= 100) and (distance <= 100) and not earlier_invalid and not earlier_free
        cond = (order_total >= 50 or is_member) and not earlier_invalid and not earlier_free and not earlier_std
        if cond:
            return 0
        need_order = max(0, 50 - order_total)
        need_member = 0 if is_member else 1
        base = min(need_order, need_member)
        penalty = 1 if earlier_invalid or earlier_free or earlier_std else 0
        return max(0, base + penalty)

    if target == "no_discount":
        earlier_invalid = (order_total < 0) or (distance < 0)
        earlier_free = (order_total >= 200) and (distance <= 50) and is_member
        earlier_std = (order_total >= 100) and (distance <= 100) and not earlier_invalid and not earlier_free
        earlier_small = (order_total >= 50 or is_member) and not earlier_invalid and not earlier_free and not earlier_std
        cond = not (earlier_invalid or earlier_free or earlier_std or earlier_small)
        if cond:
            return 0
        return 1

    raise ValueError("Unknown target: " + str(target))

# ================================================================================
# Original function: sign_type
# Fitness function: fitness_sign_type
# LLM targets: ['positive', 'negative', 'zero']
# Notes: Fitness function returns 0 only when the original sign_type would return the corresponding label; otherwise it returns a positive branch-distance-like value.
# ================================================================================

TARGETS_sign_type = ["positive", "negative", "zero"]

def fitness_sign_type(chromosome, target):
    x = chromosome[0]
    eps = 1e-6
    if target == "positive":
        if x > 0:
            return 0
        else:
            return max(0, -x + eps)
    elif target == "negative":
        if x < 0:
            return 0
        else:
            return max(0, x + eps)
    elif target == "zero":
        if x == 0:
            return 0
        else:
            return abs(x)
    else:
        raise ValueError("Unknown target: {}".format(target))

# ================================================================================
# Original function: string_category
# Fitness function: fitness_string_category
# LLM targets: ['empty', 'long_palindrome', 'short_palindrome', 'long_non_palindrome', 'other']
# Notes: Fitness function returns 0 exactly when the original function would return the specified label; otherwise returns a positive branch‑distance‑like value.
# ================================================================================

def fitness_string_category(chromosome, target):
    s = chromosome[0]
    length = len(s)
    is_pal = s == s[::-1]
    # basic distances
    empty_dist = max(0, length)
    palindrome_dist = 0 if is_pal else 1
    # length related distances
    long_pal_len_dist = max(0, 4 - length)          # need length > 3
    short_pal_len_dist = max(0, length - 3)         # need length <= 3
    short_pal_empty_dist = max(0, 1 - length)      # need not empty
    long_nonpal_len_dist = max(0, 6 - length)      # need length > 5
    other_len_dist = max(0, length - 5)            # need length <= 5

    if target == "empty":
        return 0 if length == 0 else empty_dist
    elif target == "long_palindrome":
        dist = palindrome_dist + long_pal_len_dist
        return 0 if (is_pal and length > 3) else max(0, dist)
    elif target == "short_palindrome":
        dist = palindrome_dist + short_pal_len_dist + short_pal_empty_dist
        return 0 if (is_pal and 0 < length <= 3) else max(0, dist)
    elif target == "long_non_palindrome":
        dist = (0 if not is_pal else 1) + long_nonpal_len_dist
        return 0 if (not is_pal and length > 5) else max(0, dist)
    elif target == "other":
        dist = (0 if not is_pal else 1) + other_len_dist
        return 0 if (not is_pal and 0 < length <= 5) else max(0, dist)
    else:
        raise ValueError("Unknown target: " + str(target))

# ================================================================================
# Original function: transaction_pattern
# Fitness function: fitness_transaction_pattern
# LLM targets: ['empty', 'contains_zero', 'many_large_deposits', 'many_large_withdrawals', 'mixed_transactions', 'simple_pattern']
# Notes: Fitness function returns 0 only when the chromosome would cause the original function to return the specified target; otherwise returns a positive branch-distance-like value.
# ================================================================================

def fitness_transaction_pattern(chromosome, target):
    amounts = chromosome[0]
    length = len(amounts)
    any_zero = any(x == 0 for x in amounts)
    positives = sum(1 for x in amounts if x > 0)
    negatives = sum(1 for x in amounts if x < 0)
    total = sum(amounts)

    if target == "empty":
        return max(0, length)
    if target == "contains_zero":
        return 0 if any_zero else 1
    if target == "many_large_deposits":
        d1 = max(0, 3 - positives)
        d2 = max(0, negatives)
        d3 = max(0, 101 - total)
        return d1 + d2 + d3
    if target == "many_large_withdrawals":
        d1 = max(0, 2 - negatives)
        d2 = max(0, total + 51)
        return d1 + d2
    if target == "mixed_transactions":
        d1 = max(0, 1 - positives)
        d2 = max(0, 1 - negatives)
        return d1 + d2
    if target == "simple_pattern":
        cond_empty = (length == 0)
        cond_zero = any_zero
        cond_deposits = (positives >= 3 and negatives == 0 and total > 100)
        cond_withdrawals = (negatives >= 2 and total < -50)
        cond_mixed = (positives > 0 and negatives > 0)
        if not (cond_empty or cond_zero or cond_deposits or cond_withdrawals or cond_mixed):
            return 0
        else:
            return 1
    raise ValueError("Unknown target")

# ================================================================================
# Original function: triangle_type
# Fitness function: fitness_triangle_type
# LLM targets: ['invalid_side', 'not_triangle', 'equilateral', 'isosceles', 'scalene']
# Notes: The fitness function computes a non‑negative distance for each possible return label of triangle_type. Zero distance is returned exactly when the chromosome would cause the original function to return the selected target.
# ================================================================================

def fitness_triangle_type(chromosome, target):
    a, b, c = chromosome[0], chromosome[1], chromosome[2]
    # distance for invalid side (any side <= 0)
    invalid_dist = 0 if (a <= 0 or b <= 0 or c <= 0) else min(a, b, c)
    # distances for not_triangle (triangle inequality violations)
    d1 = max(0, (a + b) - c)
    d2 = max(0, (a + c) - b)
    d3 = max(0, (b + c) - a)
    not_tri_dist = min(d1, d2, d3)
    if any(x <= 0 for x in (a, b, c)):
        not_tri_dist = 1000  # large penalty when sides are invalid
    # distance for equilateral (all sides equal)
    eq_dist = abs(a - b) + abs(b - c)
    # distances for isosceles (any two sides equal, but not all three)
    pair_diffs = [abs(a - b), abs(a - c), abs(b - c)]
    iso_min = min(pair_diffs)
    iso_dist = iso_min if iso_min > 0 else 1  # penalize the equilateral case
    # distance for scalene (all sides different)
    scalene_dist = 0 if iso_min > 0 else 1
    if target == "invalid_side":
        return max(0, invalid_dist)
    elif target == "not_triangle":
        return max(0, not_tri_dist)
    elif target == "equilateral":
        base = eq_dist
        if a <= 0 or b <= 0 or c <= 0:
            base += 1000
        if (a + b <= c) or (a + c <= b) or (b + c <= a):
            base += 1000
        return max(0, base)
    elif target == "isosceles":
        base = iso_dist
        if a <= 0 or b <= 0 or c <= 0:
            base += 1000
        if (a + b <= c) or (a + c <= b) or (b + c <= a):
            base += 1000
        return max(0, base)
    elif target == "scalene":
        base = scalene_dist
        if a <= 0 or b <= 0 or c <= 0:
            base += 1000
        if (a + b <= c) or (a + c <= b) or (b + c <= a):
            base += 1000
        return max(0, base)
    else:
        raise ValueError("Unknown target: " + str(target))

# ================================================================================
# Original function: username_category
# Fitness function: fitness_username_category
# LLM targets: ['empty', 'too_short', 'starts_with_digit', 'strong_username', 'medium_username', 'weak_username']
# Notes: 
# ================================================================================

TARGETS_username_category = [
    "empty",
    "too_short",
    "starts_with_digit",
    "strong_username",
    "medium_username",
    "weak_username"
]

def fitness_username_category(chromosome, target):
    if not isinstance(chromosome, list) or len(chromosome) != 1:
        raise ValueError("Chromosome must be a list with one element")
    username = chromosome[0]
    if not isinstance(username, str):
        raise ValueError("username must be a string")
    len_u = len(username)
    has_digit = any(ch.isdigit() for ch in username)
    has_upper = any(ch.isupper() for ch in username)
    has_special = any(not ch.isalnum() for ch in username)
    first_char_digit = username[0].isdigit() if len_u > 0 else False

    if target == "empty":
        return max(0, len_u)
    elif target == "too_short":
        if len_u == 0:
            return 1
        return max(0, len_u - 4)
    elif target == "starts_with_digit":
        dist_len = max(0, 5 - len_u)
        dist_digit = 0 if first_char_digit else 1
        return dist_len + dist_digit
    elif target == "strong_username":
        dist_len10 = max(0, 10 - len_u)
        dist_digit = 0 if has_digit else 1
        dist_upper = 0 if has_upper else 1
        dist_special = 0 if has_special else 1
        dist_len5 = max(0, 5 - len_u)
        dist_not_digit_start = 0 if not first_char_digit else 1
        return dist_len10 + dist_digit + dist_upper + dist_special + dist_len5 + dist_not_digit_start
    elif target == "medium_username":
        dist_digit = 0 if has_digit else 1
        dist_upper = 0 if has_upper else 1
        dist_len5 = max(0, 5 - len_u)
        dist_not_digit_start = 0 if not first_char_digit else 1
        strong_cond = (len_u >= 10 and has_digit and has_upper and has_special)
        dist_avoid_strong = 0 if not strong_cond else 1
        return dist_digit + dist_upper + dist_len5 + dist_not_digit_start + dist_avoid_strong
    elif target == "weak_username":
        dist_empty = 0 if len_u != 0 else 1
        dist_too_short = 0 if len_u >= 5 else 1
        dist_start_digit = 0 if not first_char_digit else 1
        strong_cond = (len_u >= 10 and has_digit and has_upper and has_special)
        dist_strong = 0 if not strong_cond else 1
        medium_cond = (has_digit and has_upper)
        dist_medium = 0 if not medium_cond else 1
        return dist_empty + dist_too_short + dist_start_digit + dist_strong + dist_medium
    else:
        raise ValueError(f"Unknown target: {target}")

# ================================================================================
# Unified fitness interface
# ================================================================================

def evaluate_fitness(function_name, chromosome, target):
    if function_name == 'bmi_category':
        return fitness_bmi_category(chromosome, target)
    elif function_name == 'list_pattern':
        return fitness_list_pattern(chromosome, target)
    elif function_name == 'number_kind':
        return fitness_number_kind(chromosome, target)
    elif function_name == 'password_strength':
        return fitness_password_strength(chromosome, target)
    elif function_name == 'pin_pattern':
        return fitness_pin_pattern(chromosome, target)
    elif function_name == 'shipping_discount':
        return fitness_shipping_discount(chromosome, target)
    elif function_name == 'sign_type':
        return fitness_sign_type(chromosome, target)
    elif function_name == 'string_category':
        return fitness_string_category(chromosome, target)
    elif function_name == 'transaction_pattern':
        return fitness_transaction_pattern(chromosome, target)
    elif function_name == 'triangle_type':
        return fitness_triangle_type(chromosome, target)
    elif function_name == 'username_category':
        return fitness_username_category(chromosome, target)
    else:
        raise ValueError(f'Unknown function name: {function_name}')
