# generated_fitness_zero_shot.py
# Generated by generate_fitness_zero_shot.py
# One-function-at-a-time zero-shot LLM fitness generation.

GENERATED_TARGETS = {
    'bmi_category': ['invalid_height', 'underweight', 'normal', 'overweight', 'obese'],
    'list_pattern': ['too_short', 'sorted_with_duplicates', 'sorted_unique', 'unsorted_with_duplicates', 'unsorted_unique'],
    'number_kind': ['zero', 'even', 'odd'],
    'password_strength': ['weak_short', 'strong', 'medium', 'weak_no_digit_upper'],
    'pin_pattern': ['secret_pin', 'all_same', 'ordered_sum_20', 'other'],
    'sign_type': ['positive', 'negative', 'zero'],
    'string_category': ['empty', 'long_palindrome', 'short_palindrome', 'long_non_palindrome', 'other'],
    'transaction_pattern': ['empty', 'contains_zero', 'many_large_deposits', 'many_large_withdrawals', 'mixed_transactions', 'simple_pattern'],
    'username_category': ['empty', 'too_short', 'starts_with_digit', 'strong_username', 'medium_username', 'weak_username'],
}

GENERATED_INPUT_SCHEMAS = {
    'bmi_category': [{'type': 'float', 'min': 0.0, 'max': 3000.0}, {'type': 'float', 'min': 0.0, 'max': 3000.0}],
    'list_pattern': [{'type': 'list_int', 'min': -100.0, 'max': 100.0, 'min_len': 0, 'max_len': 6}],
    'number_kind': [{'type': 'int', 'min': -500.0, 'max': 3000.0}],
    'password_strength': [{'type': 'str', 'min_len': 0, 'max_len': 15}],
    'pin_pattern': [{'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'int', 'min': -500.0, 'max': 3000.0}],
    'sign_type': [{'type': 'int', 'min': -500.0, 'max': 3000.0}],
    'string_category': [{'type': 'str', 'min_len': 0, 'max_len': 15}],
    'transaction_pattern': [{'type': 'list_int', 'min': -100.0, 'max': 100.0, 'min_len': 0, 'max_len': 6}],
    'username_category': [{'type': 'str', 'min_len': 0, 'max_len': 15}],
}

# ================================================================================
# Original function: bmi_category
# Fitness function: fitness_bmi_category
# LLM targets: ['invalid_height', 'underweight', 'normal', 'overweight', 'obese']
# Notes: Branch-distance style fitness function for bmi_category covering all return labels.
# ================================================================================

def fitness_bmi_category(chromosome, target):
    weight = chromosome[0]
    height = chromosome[1]
    if target == "invalid_height":
        return max(0.0, height)
    height_penalty = max(0.0, -height + 1e-6)
    if height > 0:
        bmi = weight / (height * height)
    else:
        bmi = 0.0
    if target == "underweight":
        return height_penalty + max(0.0, bmi - 18.5)
    if target == "normal":
        return height_penalty + max(0.0, 18.5 - bmi) + max(0.0, bmi - 25.0)
    if target == "overweight":
        return height_penalty + max(0.0, 25.0 - bmi) + max(0.0, bmi - 30.0)
    if target == "obese":
        return height_penalty + max(0.0, 30.0 - bmi)
    raise ValueError("Unknown target: " + str(target))

# ================================================================================
# Original function: list_pattern
# Fitness function: fitness_list_pattern
# LLM targets: ['too_short', 'sorted_with_duplicates', 'sorted_unique', 'unsorted_with_duplicates', 'unsorted_unique']
# Notes: The fitness function returns 0 exactly when the input list triggers the corresponding return label of the original function. Positive integer distances indicate how far the input is from satisfying the required conditions (length, sortedness, duplicate presence).
# ================================================================================

def fitness_list_pattern(chromosome, target):
    nums = chromosome[0]
    len_nums = len(nums)
    # distance for the "too_short" target (len < 2)
    len_dist_too_short = max(0, len_nums - 1)
    # distance for all other targets (need at least length 2)
    len_dist_other = max(0, 2 - len_nums)
    # sorted check
    is_sorted = nums == sorted(nums)
    sorted_dist = 0 if is_sorted else 1
    not_sorted_dist = 0 if not is_sorted else 1
    # duplicate check
    has_dup = len_nums != len(set(nums))
    dup_dist = 0 if has_dup else 1
    no_dup_dist = 0 if not has_dup else 1
    if target == "too_short":
        return len_dist_too_short
    elif target == "sorted_unique":
        return len_dist_other + sorted_dist + no_dup_dist
    elif target == "sorted_with_duplicates":
        return len_dist_other + sorted_dist + dup_dist
    elif target == "unsorted_unique":
        return len_dist_other + not_sorted_dist + no_dup_dist
    elif target == "unsorted_with_duplicates":
        return len_dist_other + not_sorted_dist + dup_dist
    else:
        raise ValueError("Unknown target: " + str(target))

# ================================================================================
# Original function: number_kind
# Fitness function: fitness_number_kind
# LLM targets: ['zero', 'even', 'odd']
# Notes: The fitness function returns 0 exactly when the original function would return the specified label. Positive integer distances indicate how far the input is from satisfying the branch conditions.
# ================================================================================

def fitness_number_kind(chromosome, target):
    # Extract argument
    x = chromosome[0]
    if target == "zero":
        # distance is absolute difference from 0
        distance = abs(x - 0)
        return max(0, distance)
    elif target == "even":
        # need x != 0 and x % 2 == 0
        mod_distance = 0 if x % 2 == 0 else 1
        zero_penalty = 1 if x == 0 else 0
        distance = mod_distance + zero_penalty
        return max(0, distance)
    elif target == "odd":
        # need x % 2 != 0
        distance = 0 if x % 2 != 0 else 1
        return max(0, distance)
    else:
        raise ValueError("Unknown target: {}".format(target))

# ================================================================================
# Original function: password_strength
# Fitness function: fitness_password_strength
# LLM targets: ['weak_short', 'strong', 'medium', 'weak_no_digit_upper']
# Notes: Branch-distance fitness function that returns 0 exactly when the original password_strength function would return the selected label.
# ================================================================================

def fitness_password_strength(chromosome, target):
    s = chromosome[0]
    length = len(s)
    has_digit = any(ch.isdigit() for ch in s)
    has_upper = any(ch.isupper() for ch in s)

    if target == "weak_short":
        # Need length < 6
        return max(0, length - 5)
    elif target == "strong":
        # Need length >= 10, at least one digit, and at least one uppercase
        dist_len = max(0, 10 - length)
        dist_digit = 0 if has_digit else 1
        dist_upper = 0 if has_upper else 1
        return dist_len + dist_digit + dist_upper
    elif target == "medium":
        # Need length >= 6, (digit or upper) true, but NOT strong condition
        dist_len = max(0, 6 - length)
        dist_digit_upper = 0 if (has_digit or has_upper) else 1
        dist_not_strong = 0 if not (length >= 10 and has_digit and has_upper) else 1
        return dist_len + dist_digit_upper + dist_not_strong
    elif target == "weak_no_digit_upper":
        # Need length >= 6 and no digit and no uppercase
        dist_len = max(0, 6 - length)
        dist_digit_upper = 0 if not (has_digit or has_upper) else 1
        return dist_len + dist_digit_upper
    else:
        raise ValueError("Unknown target: " + str(target))

# ================================================================================
# Original function: pin_pattern
# Fitness function: fitness_pin_pattern
# LLM targets: ['secret_pin', 'all_same', 'ordered_sum_20', 'other']
# Notes: Fitness function returns 0 exactly when the chromosome would cause the original function to return the specified label; otherwise it returns a positive branch‑distance‑like value.
# ================================================================================

def fitness_pin_pattern(chromosome, target):
    a, b, c, d = chromosome
    # distance to secret_pin condition
    dist_secret = max(0, abs(a - 7)) + max(0, abs(b - 3)) + max(0, abs(c - 9)) + max(0, abs(d - 1))
    # distance to all_same condition
    dist_all_same = max(abs(a - b), abs(a - c), abs(a - d))
    # distance to ordered_sum_20 condition
    sum_vals = a + b + c + d
    dist_sum = abs(sum_vals - 20)
    order_viol = max(0, a - b + 1) + max(0, b - c + 1) + max(0, c - d + 1)
    dist_ordered = dist_sum + order_viol
    if target == "secret_pin":
        return dist_secret
    elif target == "all_same":
        return dist_all_same
    elif target == "ordered_sum_20":
        return dist_ordered
    elif target == "other":
        if dist_secret == 0 or dist_all_same == 0 or dist_ordered == 0:
            return 1
        else:
            return 0
    else:
        raise ValueError("Unknown target: " + str(target))

# ================================================================================
# Original function: sign_type
# Fitness function: fitness_sign_type
# LLM targets: ['positive', 'negative', 'zero']
# Notes: Fitness function returns 0 only when the original sign_type would return the specified label; otherwise returns a positive branch-distance value.
# ================================================================================

TARGETS_sign_type = ["positive", "negative", "zero"]

def fitness_sign_type(chromosome, target):
    x = chromosome[0]
    if target == "positive":
        if x > 0:
            return 0
        else:
            return max(0, -x + 1e-6)
    elif target == "negative":
        if x < 0:
            return 0
        else:
            return max(0, x + 1e-6)
    elif target == "zero":
        if x == 0:
            return 0
        else:
            return abs(x)
    else:
        raise ValueError("Unknown target: " + str(target))

# ================================================================================
# Original function: string_category
# Fitness function: fitness_string_category
# LLM targets: ['empty', 'long_palindrome', 'short_palindrome', 'long_non_palindrome', 'other']
# Notes: Fitness returns 0 exactly when the original function would return the specified label; otherwise a positive branch‑distance‑like value.
# ================================================================================

def fitness_string_category(chromosome, target):
    s = chromosome[0]
    length = len(s)
    is_pal = s == s[::-1]
    if target == "empty":
        distance = length
    elif target == "long_palindrome":
        if not is_pal:
            distance = 1
        else:
            distance = max(0, 4 - length)
    elif target == "short_palindrome":
        if not is_pal:
            distance = 1
        else:
            distance = max(0, length - 3)
    elif target == "long_non_palindrome":
        if is_pal:
            distance = 1
        else:
            distance = max(0, 6 - length)
    elif target == "other":
        distance = (1 if length == 0 else 0) + (1 if is_pal else 0) + max(0, length - 5)
    else:
        raise ValueError("Unknown target: " + str(target))
    return max(0, distance)

# ================================================================================
# Original function: transaction_pattern
# Fitness function: fitness_transaction_pattern
# LLM targets: ['empty', 'contains_zero', 'many_large_deposits', 'many_large_withdrawals', 'mixed_transactions', 'simple_pattern']
# Notes: Fitness function returns 0 only when the chromosome would cause the original function to return the specified target; otherwise returns a positive branch‑distance‑like value.
# ================================================================================

def fitness_transaction_pattern(chromosome, target):
    amounts = chromosome[0]
    length = len(amounts)
    any_zero = any(x == 0 for x in amounts)
    positives = sum(1 for x in amounts if x > 0)
    negatives = sum(1 for x in amounts if x < 0)
    total = sum(amounts)
    if target == "empty":
        return max(0, length)
    if target == "contains_zero":
        return 0 if any_zero else 1
    if target == "many_large_deposits":
        d1 = max(0, 3 - positives)
        d2 = max(0, negatives)
        d3 = max(0, 101 - total)
        return d1 + d2 + d3
    if target == "many_large_withdrawals":
        d1 = max(0, 2 - negatives)
        d2 = max(0, total + 51)
        return d1 + d2
    if target == "mixed_transactions":
        d1 = max(0, 1 - positives)
        d2 = max(0, 1 - negatives)
        return d1 + d2
    if target == "simple_pattern":
        d_len = max(0, 1 - length)
        d_zero = 0 if not any_zero else 1
        d_deposits = 0 if not (positives >= 3 and negatives == 0 and total > 100) else 1
        d_withdrawals = 0 if not (negatives >= 2 and total < -50) else 1
        d_mixed = 0 if not (positives > 0 and negatives > 0) else 1
        return d_len + d_zero + d_deposits + d_withdrawals + d_mixed
    raise ValueError("Unknown target")

# ================================================================================
# Original function: username_category
# Fitness function: fitness_username_category
# LLM targets: ['empty', 'too_short', 'starts_with_digit', 'strong_username', 'medium_username', 'weak_username']
# Notes: Fitness function returns 0 exactly when the original function would return the specified label and positive distances otherwise.
# ================================================================================

def fitness_username_category(chromosome, target):
    username = chromosome[0]
    length = len(username)
    has_digit = any(ch.isdigit() for ch in username)
    has_upper = any(ch.isupper() for ch in username)
    has_special = any(not ch.isalnum() for ch in username)
    starts_digit = length > 0 and username[0].isdigit()

    if target == "empty":
        return max(0, length)

    elif target == "too_short":
        if length == 0:
            return 1
        return max(0, length - 4)

    elif target == "starts_with_digit":
        if length == 0:
            return 1
        return 0 if starts_digit else 1

    elif target == "strong_username":
        dist = max(0, 10 - length)
        dist += 0 if has_digit else 1
        dist += 0 if has_upper else 1
        dist += 0 if has_special else 1
        if length == 0 or length < 5 or starts_digit:
            dist += 10
        return dist

    elif target == "medium_username":
        dist = 0 if has_digit else 1
        dist += 0 if has_upper else 1
        if length >= 10 and has_digit and has_upper and has_special:
            dist += 10
        if length == 0 or length < 5 or starts_digit:
            dist += 10
        return dist

    elif target == "weak_username":
        if length == 0 or length < 5 or starts_digit:
            return 1
        if length >= 10 and has_digit and has_upper and has_special:
            return 1
        if has_digit and has_upper:
            return 1
        return 0

    else:
        raise ValueError("Unknown target")

# ================================================================================
# Unified fitness interface
# ================================================================================

def evaluate_fitness(function_name, chromosome, target):
    if function_name == 'bmi_category':
        return fitness_bmi_category(chromosome, target)
    elif function_name == 'list_pattern':
        return fitness_list_pattern(chromosome, target)
    elif function_name == 'number_kind':
        return fitness_number_kind(chromosome, target)
    elif function_name == 'password_strength':
        return fitness_password_strength(chromosome, target)
    elif function_name == 'pin_pattern':
        return fitness_pin_pattern(chromosome, target)
    elif function_name == 'sign_type':
        return fitness_sign_type(chromosome, target)
    elif function_name == 'string_category':
        return fitness_string_category(chromosome, target)
    elif function_name == 'transaction_pattern':
        return fitness_transaction_pattern(chromosome, target)
    elif function_name == 'username_category':
        return fitness_username_category(chromosome, target)
    else:
        raise ValueError(f'Unknown function name: {function_name}')
