# generated_fitness_no_semantic_openai_gpt_oss_20b.py
# Generated by generate_fitness_zero_shot.py
# Provider: groq
# Model: openai/gpt-oss-20b
# Fitness version: without_semantic_validation
# One-function-at-a-time LLM fitness generation.

GENERATED_TARGETS = {
    'number_kind': ['zero', 'even', 'odd'],
    'sign_type': ['positive', 'negative', 'zero'],
    'transaction_pattern': ['empty', 'contains_zero', 'many_large_deposits', 'many_large_withdrawals', 'mixed_transactions', 'simple_pattern'],
}

GENERATED_INPUT_SCHEMAS = {
    'number_kind': [{'type': 'int', 'min': -500.0, 'max': 3000.0}],
    'sign_type': [{'type': 'int', 'min': -500.0, 'max': 3000.0}],
    'transaction_pattern': [{'type': 'list_int', 'min': -100.0, 'max': 100.0, 'min_len': 0, 'max_len': 6}],
}

# ================================================================================
# Original function: number_kind
# Fitness function: fitness_number_kind
# LLM targets: ['zero', 'even', 'odd']
# Notes: 
# ================================================================================

TARGETS_number_kind = ["zero", "even", "odd"]

def fitness_number_kind(chromosome, target):
    if target not in TARGETS_number_kind:
        raise ValueError("Unknown target: " + target)
    x = chromosome[0]
    if target == "zero":
        distance = abs(x)
    elif target == "even":
        if x == 0:
            distance = 1
        else:
            distance = abs(x % 2)
    else:  # odd
        if x == 0:
            distance = 1
        else:
            distance = abs((x % 2) - 1)
    return max(0, distance)

# ================================================================================
# Original function: sign_type
# Fitness function: fitness_sign_type
# LLM targets: ['positive', 'negative', 'zero']
# Notes: 
# ================================================================================

TARGETS_sign_type = ["positive", "negative", "zero"]

def fitness_sign_type(chromosome, target):
    if not chromosome:
        raise ValueError("Chromosome must contain at least one element.")
    x = chromosome[0]
    if target == "positive":
        if x > 0:
            return 0
        else:
            return max(0, 0 - x) + 1
    elif target == "negative":
        if x < 0:
            return 0
        else:
            return max(0, x) + 1
    elif target == "zero":
        if x == 0:
            return 0
        else:
            return abs(x)
    else:
        raise ValueError(f"Unknown target: {target}")

# ================================================================================
# Original function: transaction_pattern
# Fitness function: fitness_transaction_pattern
# LLM targets: ['empty', 'contains_zero', 'many_large_deposits', 'many_large_withdrawals', 'mixed_transactions', 'simple_pattern']
# Notes: 
# ================================================================================

def fitness_transaction_pattern(chromosome, target):
    # chromosome is expected to be a list of integers
    amounts = chromosome
    length = len(amounts)
    positives = sum(1 for x in amounts if x > 0)
    negatives = sum(1 for x in amounts if x < 0)
    total = sum(amounts)

    # Distance to 'empty'
    dist_empty = 0 if length == 0 else 1

    # Distance to 'contains_zero'
    if any(x == 0 for x in amounts):
        dist_contains_zero = 0
    else:
        # distance based on how close any element is to zero
        dist_contains_zero = min(abs(x) for x in amounts) if amounts else 1

    # Distance to 'many_large_deposits'
    d1 = max(0, 3 - positives)          # need at least 3 positives
    d2 = max(0, negatives)              # negatives must be 0
    d3 = max(0, 100 - total)            # total must be > 100
    dist_many_large_deposits = d1 + d2 + d3

    # Distance to 'many_large_withdrawals'
    d4 = max(0, 2 - negatives)          # need at least 2 negatives
    d5 = max(0, total + 50)             # total must be < -50
    dist_many_large_withdrawals = d4 + d5

    # Distance to 'mixed_transactions'
    d6 = max(0, 1 - positives)          # need at least one positive
    d7 = max(0, 1 - negatives)          # need at least one negative
    dist_mixed_transactions = d6 + d7

    # Distance to 'simple_pattern'
    # simple_pattern occurs only if none of the above conditions are satisfied
    if dist_empty == 0 or dist_contains_zero == 0 or dist_many_large_deposits == 0 or dist_many_large_withdrawals == 0 or dist_mixed_transactions == 0:
        dist_simple_pattern = 1
    else:
        dist_simple_pattern = 0

    # Map target names to distances
    distances = {
        "empty": dist_empty,
        "contains_zero": dist_contains_zero,
        "many_large_deposits": dist_many_large_deposits,
        "many_large_withdrawals": dist_many_large_withdrawals,
        "mixed_transactions": dist_mixed_transactions,
        "simple_pattern": dist_simple_pattern
    }

    if target not in distances:
        raise ValueError(f"Unknown target: {target}")

    return distances[target]

# ================================================================================
# Unified fitness interface
# ================================================================================

def evaluate_fitness(function_name, chromosome, target):
    if function_name == 'number_kind':
        return fitness_number_kind(chromosome, target)
    elif function_name == 'sign_type':
        return fitness_sign_type(chromosome, target)
    elif function_name == 'transaction_pattern':
        return fitness_transaction_pattern(chromosome, target)
    else:
        raise ValueError(f'Unknown function name: {function_name}')
