# generated_fitness_zero_shot.py
# Generated by generate_fitness_zero_shot.py
# One-function-at-a-time zero-shot LLM fitness generation.

GENERATED_TARGETS = {
    'bmi_category': ['invalid_height', 'underweight', 'normal', 'overweight', 'obese'],
    'list_pattern': ['too_short', 'sorted_with_duplicates', 'sorted_unique', 'unsorted_with_duplicates', 'unsorted_unique'],
    'number_kind': ['zero', 'even', 'odd'],
    'password_strength': ['weak_short', 'strong', 'medium', 'weak_no_digit_upper'],
    'pin_pattern': ['secret_pin', 'all_same', 'ordered_sum_20', 'other'],
    'shipping_discount': ['invalid', 'free_express_shipping', 'standard_discount', 'small_discount', 'no_discount'],
    'sign_type': ['positive', 'negative', 'zero'],
    'string_category': ['empty', 'long_palindrome', 'short_palindrome', 'long_non_palindrome', 'other'],
    'triangle_type': ['invalid_side', 'not_triangle', 'equilateral', 'isosceles', 'scalene'],
    'username_category': ['empty', 'too_short', 'starts_with_digit', 'strong_username', 'medium_username', 'weak_username'],
}

GENERATED_INPUT_SCHEMAS = {
    'bmi_category': [{'type': 'float', 'min': 0.0, 'max': 300.0}, {'type': 'float', 'min': 0.0, 'max': 3.0}],
    'list_pattern': [{'type': 'list_int', 'min_len': 0, 'max_len': 6}],
    'number_kind': [{'type': 'int', 'min': -500.0, 'max': 3000.0}],
    'password_strength': [{'type': 'str', 'min_len': 0, 'max_len': 15}],
    'pin_pattern': [{'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'int', 'min': -500.0, 'max': 3000.0}],
    'shipping_discount': [{'type': 'float', 'min': -100.0, 'max': 500.0}, {'type': 'float', 'min': -100.0, 'max': 200.0}, {'type': 'bool'}],
    'sign_type': [{'type': 'int', 'min': -500.0, 'max': 500.0}],
    'string_category': [{'type': 'str', 'min_len': 0, 'max_len': 15}],
    'triangle_type': [{'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'int', 'min': -500.0, 'max': 3000.0}, {'type': 'int', 'min': -500.0, 'max': 3000.0}],
    'username_category': [{'type': 'str', 'min_len': 0, 'max_len': 20}],
}

# ================================================================================
# Original function: bmi_category
# Fitness function: fitness_bmi_category
# LLM targets: ['invalid_height', 'underweight', 'normal', 'overweight', 'obese']
# Notes: The fitness function calculates the sum of branch distances for the conditions that must be met to reach the specified target path. For each target, it sums the distances for 'height > 0' (unless the target is 'invalid_height') and the BMI range conditions. A small constant K (1.0) is added for strict inequalities to ensure a positive distance when the condition is not strictly met. The fitness is 0 if and only if all conditions for the target path are satisfied. A helper `bmi_calc` is included to recompute BMI.
# ================================================================================

def fitness_bmi_category(chromosome, target):
    weight, height = chromosome
    K = 1.0

    def bd_lt(left, right):
        val = left - right
        return 0.0 if val < 0 else val + K

    def bd_le(left, right):
        val = left - right
        return 0.0 if val <= 0 else val

    def bd_gt(left, right):
        val = right - left
        return 0.0 if val < 0 else val + K

    def bd_ge(left, right):
        val = right - left
        return 0.0 if val <= 0 else val

    if target == "invalid_height":
        return bd_le(height, 0.0)

    dist_height_gt_0 = bd_gt(height, 0.0)

    if target == "underweight":
        return dist_height_gt_0 + bd_lt(bmi_calc(weight, height), 18.5)

    if target == "normal":
        return dist_height_gt_0 + bd_ge(bmi_calc(weight, height), 18.5) + bd_lt(bmi_calc(weight, height), 25.0)

    if target == "overweight":
        return dist_height_gt_0 + bd_ge(bmi_calc(weight, height), 25.0) + bd_lt(bmi_calc(weight, height), 30.0)

    if target == "obese":
        return dist_height_gt_0 + bd_ge(bmi_calc(weight, height), 30.0)

    raise ValueError("Unknown target: " + target)

def bmi_calc(weight, height):
    # Replicate BMI calculation to avoid calling original function
    # Assume height > 0 due to previous branch distance checks
    return weight / (height * height)

# ================================================================================
# Original function: list_pattern
# Fitness function: fitness_list_pattern
# LLM targets: ['too_short', 'sorted_with_duplicates', 'sorted_unique', 'unsorted_with_duplicates', 'unsorted_unique']
# Notes: The fitness function was corrected for the 'unsorted' branches. Specifically, 'bd_nums_eq_sorted_false' was adjusted to return 0 when the list is actually unsorted (list_diff_sum > 0) and K when it is sorted (list_diff_sum == 0). This ensures a fitness of 0 exactly when the 'nums != sorted(nums)' condition is met, addressing the previous semantic mismatch.
# ================================================================================

def fitness_list_pattern(chromosome, target):
    nums = chromosome[0]
    K = 1.0

    len_nums = len(nums)
    
    sorted_nums = sorted(nums)
    list_diff_sum = 0
    if len_nums > 0:
        for i in range(len_nums):
            list_diff_sum += abs(nums[i] - sorted_nums[i])

    len_unique_nums = len(set(nums))
    num_duplicates_delta = len_nums - len_unique_nums

    # Branch Distance for 'len(nums) < 2'
    # True path: len(nums) < 2
    bd_len_lt_2_true = max(0.0, len_nums - 2 + K)
    # False path: len(nums) >= 2
    bd_len_lt_2_false = max(0.0, 2 - len_nums)

    # Branch Distance for 'nums == sorted(nums)'
    # True path: nums == sorted(nums) (list is sorted)
    bd_nums_eq_sorted_true = float(list_diff_sum)
    # False path: nums != sorted(nums) (list is not sorted)
    # This is fixed to be 0 when list is actually unsorted, and K otherwise.
    bd_nums_eq_sorted_false = (K if list_diff_sum == 0 else 0.0)

    # Branch Distance for 'len(nums) != len(set(nums))' (has duplicates)
    # True path: len(nums) != len(set(nums)) (list has duplicates)
    bd_duplicates_true = max(0.0, K - num_duplicates_delta)
    # False path: len(nums) == len(set(nums)) (list has no duplicates)
    bd_duplicates_false = float(num_duplicates_delta)

    # Combine branch distances for each target
    if target == "too_short":
        return bd_len_lt_2_true
    elif target == "sorted_with_duplicates":
        return bd_len_lt_2_false + bd_nums_eq_sorted_true + bd_duplicates_true
    elif target == "sorted_unique":
        return bd_len_lt_2_false + bd_nums_eq_sorted_true + bd_duplicates_false
    elif target == "unsorted_with_duplicates":
        return bd_len_lt_2_false + bd_nums_eq_sorted_false + bd_duplicates_true
    elif target == "unsorted_unique":
        return bd_len_lt_2_false + bd_nums_eq_sorted_false + bd_duplicates_false
    else:
        raise ValueError("Unknown target")

# ================================================================================
# Original function: number_kind
# Fitness function: fitness_number_kind
# LLM targets: ['zero', 'even', 'odd']
# Notes: The fitness function calculates the branch distance for three targets: 'zero', 'even', and 'odd'. For 'zero', it directly measures the distance to x == 0. For 'even', it combines distances to satisfy x != 0 and x % 2 == 0. For 'odd', it combines distances to satisfy x != 0 and x % 2 != 0. Helper functions normalize distances, ensuring 0.0 for satisfied conditions and positive values for unsatisfied conditions, with smaller values indicating closer proximity.
# ================================================================================

def normalize(v):
    if v == 0:
        return 0.0
    return 1.0 - (1.0 / (1.0 + v))

def branch_distance_eq(left, right):
    return normalize(abs(left - right))

def branch_distance_ne(left, right):
    if left == right:
        return 1.0
    return 0.0

def branch_distance_modulo_eq_zero(value, divisor):
    if divisor == 0:
        return 1.0
    return normalize(abs(value % divisor))

def branch_distance_modulo_ne_zero(value, divisor):
    if divisor == 0:
        return 0.0
    if value % divisor == 0:
        return 1.0
    return 0.0

def fitness_number_kind(chromosome, target):
    x = chromosome[0]

    if target == "zero":
        return branch_distance_eq(x, 0)
    elif target == "even":
        dist_x_not_zero = branch_distance_ne(x, 0)
        dist_x_mod_2_zero = branch_distance_modulo_eq_zero(x, 2)
        return dist_x_not_zero + dist_x_mod_2_zero
    elif target == "odd":
        dist_x_not_zero = branch_distance_ne(x, 0)
        dist_x_mod_2_not_zero = branch_distance_modulo_ne_zero(x, 2)
        return dist_x_not_zero + dist_x_mod_2_not_zero
    else:
        raise ValueError(f"Unknown target: {target}")

# ================================================================================
# Original function: password_strength
# Fitness function: fitness_password_strength
# LLM targets: ['weak_short', 'strong', 'medium', 'weak_no_digit_upper']
# Notes: The fitness function calculates a branch-distance-style metric for each of the four return paths. It accumulates distances for conditions that must be false to reach a target's `elif`/`else` branches, and for conditions that must be true to satisfy the target's specific branch logic. Distances are non-negative, with 0 indicating target coverage.
# ================================================================================

TARGETS_password_strength = [
    "weak_short",
    "strong",
    "medium",
    "weak_no_digit_upper"
]

def fitness_password_strength(chromosome, target):
    s = chromosome[0]
    s_len = len(s)

    def branch_dist_ge(actual, target_val):
        return max(0, target_val - actual + 1)

    def branch_dist_lt(actual, target_val):
        return max(0, actual - target_val + 1)

    def branch_dist_true(condition):
        return 0 if condition else 1

    def branch_dist_false(condition):
        return 0 if not condition else 1

    has_digit = any(ch.isdigit() for ch in s)
    has_upper = any(ch.isupper() for ch in s)

    # --- Branch 1: `if len(s) < 6:`
    if target == "weak_short":
        return branch_dist_lt(s_len, 6)
    
    # To reach any subsequent branch, `len(s) < 6` must be false.
    dist_to_skip_weak_short = branch_dist_false(s_len < 6)

    # --- Branch 2: `if len(s) >= 10 and has_digit and has_upper:`
    if target == "strong":
        dist_len_ge_10 = branch_dist_ge(s_len, 10)
        dist_has_digit = branch_dist_true(has_digit)
        dist_has_upper = branch_dist_true(has_upper)
        return dist_to_skip_weak_short + dist_len_ge_10 + dist_has_digit + dist_has_upper

    # To reach subsequent branches ("medium", "weak_no_digit_upper"),
    # we must skip "weak_short" AND skip "strong".
    # Skipping "strong" means `len(s) >= 10 and has_digit and has_upper` must be FALSE.
    # That is `len(s) < 10 OR not has_digit OR not has_upper` must be TRUE.
    dist_to_skip_strong = min(
        branch_dist_lt(s_len, 10),
        branch_dist_false(has_digit),
        branch_dist_false(has_upper)
    )

    # --- Branch 3: `elif has_digit or has_upper:`
    if target == "medium":
        dist_has_digit_or_upper = min(
            branch_dist_true(has_digit),
            branch_dist_true(has_upper)
        )
        return dist_to_skip_weak_short + dist_to_skip_strong + dist_has_digit_or_upper
    
    # To reach the final "else" branch ("weak_no_digit_upper"),
    # we must skip "weak_short" AND skip "strong" AND skip "medium".
    # Skipping "medium" means `has_digit or has_upper` must be FALSE.
    # That is `not has_digit AND not has_upper` must be TRUE.
    dist_to_skip_medium = branch_dist_false(has_digit) + branch_dist_false(has_upper)

    # --- Branch 4: `else:`
    if target == "weak_no_digit_upper":
        return dist_to_skip_weak_short + dist_to_skip_strong + dist_to_skip_medium

    raise ValueError("Unknown target: " + target)

# ================================================================================
# Original function: pin_pattern
# Fitness function: fitness_pin_pattern
# LLM targets: ['secret_pin', 'all_same', 'ordered_sum_20', 'other']
# Notes: The fitness function calculates branch distances to satisfy the conditions for each target. For 'elif' and 'else' branches, a small penalty (1.0) is added if any preceding 'if' or 'elif' condition is met, guiding the search to make those preceding conditions false. This ensures fitness is 0 only for inputs that truly reach the specific target branch.
# ================================================================================

TARGETS_pin_pattern = ["secret_pin", "all_same", "ordered_sum_20", "other"]

def fitness_pin_pattern(chromosome, target):
    a, b, c, d = chromosome[0], chromosome[1], chromosome[2], chromosome[3]

    # Helper functions for branch distance calculations
    def _cond_true_eq(left, right):
        return abs(left - right)

    def _cond_true_lt(left, right):
        # Distance to make 'left < right' true. If 'left >= right', distance is 'left - right + 1'.
        return max(0, left - right + 1)

    # Helper for 'elif' and 'else' conditions, penalizing if a prior condition was met
    def _cond_false_penalty(cond_true_fitness_val):
        # Returns a small positive penalty (1.0) if the condition was met (i.e., its fitness is 0).
        # Otherwise, returns 0, indicating the condition was not met.
        return 1.0 if cond_true_fitness_val == 0 else 0.0

    # --- Calculate fitness for each original condition to be TRUE ---

    # Condition 1: a == 7 and b == 3 and c == 9 and d == 1
    cond1_true_fitness = (
        _cond_true_eq(a, 7) +
        _cond_true_eq(b, 3) +
        _cond_true_eq(c, 9) +
        _cond_true_eq(d, 1)
    )

    # Condition 2: a == b == c == d (equivalent to a==b and b==c and c==d)
    cond2_true_fitness = (
        _cond_true_eq(a, b) +
        _cond_true_eq(b, c) +
        _cond_true_eq(c, d)
    )

    # Condition 3: a + b + c + d == 20 and a < b < c < d
    sum_abcd = a + b + c + d
    cond3_true_fitness = (
        _cond_true_eq(sum_abcd, 20) +
        _cond_true_lt(a, b) +
        _cond_true_lt(b, c) +
        _cond_true_lt(c, d)
    )

    # --- Assign fitness based on target ---
    if target == "secret_pin":
        return cond1_true_fitness
    elif target == "all_same":
        # To reach 'all_same', condition 1 must be false, and condition 2 must be true.
        return cond2_true_fitness + _cond_false_penalty(cond1_true_fitness)
    elif target == "ordered_sum_20":
        # To reach 'ordered_sum_20', condition 1 and 2 must be false, and condition 3 must be true.
        return (
            cond3_true_fitness +
            _cond_false_penalty(cond1_true_fitness) +
            _cond_false_penalty(cond2_true_fitness)
        )
    elif target == "other":
        # To reach 'other', all previous conditions must be false.
        return (
            _cond_false_penalty(cond1_true_fitness) +
            _cond_false_penalty(cond2_true_fitness) +
            _cond_false_penalty(cond3_true_fitness)
        )
    else:
        raise ValueError("Unknown target: " + target)

# ================================================================================
# Original function: shipping_discount
# Fitness function: fitness_shipping_discount
# LLM targets: ['invalid', 'free_express_shipping', 'standard_discount', 'small_discount', 'no_discount']
# Notes: Generates a branch-distance-style fitness function to cover all explicit return statements in the shipping_discount function. It includes helper functions for calculating distances for different types of conditions (e.g., <, >=, <=, boolean) and applies penalties for inputs that would satisfy higher-priority branches before reaching the target branch. no_discount is the default return, so it has 0 distance if all preceding conditions are avoided.
# ================================================================================

def fitness_shipping_discount(chromosome, target):
    order_total, distance, is_member = chromosome

    def dist_true_lt(a, b):
        return max(0.0, a - b + 1.0)

    def dist_true_geq(a, b):
        return max(0.0, b - a + 0.0)

    def dist_true_leq(a, b):
        return max(0.0, a - b + 0.0)

    def dist_true_bool(b_val):
        return 0.0 if b_val else 1.0

    # Evaluate all conditions to determine the actual path taken by the input
    cond_path_invalid = (order_total < 0) or (distance < 0)
    cond_path_free_express = (order_total >= 200) and (distance <= 50) and is_member
    cond_path_standard = (order_total >= 100) and (distance <= 100)
    cond_path_small = (order_total >= 50) or is_member

    if target == "invalid":
        # Target: order_total < 0 or distance < 0
        d_ot_lt_0 = dist_true_lt(order_total, 0)
        d_dist_lt_0 = dist_true_lt(distance, 0)
        return min(d_ot_lt_0, d_dist_lt_0)

    elif target == "free_express_shipping":
        # Conditions: order_total >= 200 AND distance <= 50 AND is_member

        # Distances for the current branch's conditions
        d_ot_geq_200 = dist_true_geq(order_total, 200)
        d_dist_leq_50 = dist_true_leq(distance, 50)
        d_is_member = dist_true_bool(is_member)
        current_branch_distance = d_ot_geq_200 + d_dist_leq_50 + d_is_member
        
        # Penalize if higher priority branches would be taken
        if cond_path_invalid:
            return current_branch_distance + 1000.0
        
        return current_branch_distance

    elif target == "standard_discount":
        # Conditions: order_total >= 100 AND distance <= 100

        # Distances for the current branch's conditions
        d_ot_geq_100 = dist_true_geq(order_total, 100)
        d_dist_leq_100 = dist_true_leq(distance, 100)
        current_branch_distance = d_ot_geq_100 + d_dist_leq_100

        # Penalize if higher priority branches would be taken
        if cond_path_invalid:
            return current_branch_distance + 10000.0
        if cond_path_free_express:
            return current_branch_distance + 5000.0
        
        return current_branch_distance

    elif target == "small_discount":
        # Conditions: order_total >= 50 OR is_member

        # Distances for the current branch's conditions
        d_ot_geq_50 = dist_true_geq(order_total, 50)
        d_is_member = dist_true_bool(is_member)
        current_branch_distance = min(d_ot_geq_50, d_is_member)

        # Penalize if higher priority branches would be taken
        if cond_path_invalid:
            return current_branch_distance + 10000.0
        if cond_path_free_express:
            return current_branch_distance + 5000.0
        if cond_path_standard:
            return current_branch_distance + 2500.0
        
        return current_branch_distance

    elif target == "no_discount":
        # This target is reached if all preceding conditions are false

        # Penalize if higher priority branches would be taken
        if cond_path_invalid:
            return 10000.0
        if cond_path_free_express:
            return 5000.0
        if cond_path_standard:
            return 2500.0
        if cond_path_small:
            return 1250.0
        
        return 0.0 # Reached

# ================================================================================
# Original function: sign_type
# Fitness function: fitness_sign_type
# LLM targets: ['positive', 'negative', 'zero']
# Notes: The fitness function guides the input `x` towards the target condition. For 'positive' and 'negative', it uses the absolute value of `x` plus a small constant to encourage crossing zero. For 'zero', it uses the absolute value of `x`.
# ================================================================================

TARGETS_sign_type = [
    "positive",
    "negative",
    "zero"
]

def fitness_sign_type(chromosome, target):
    x = chromosome[0]

    if target == "positive":
        if x > 0:
            return 0
        else:
            # Distance to make x > 0. If x is 0 or negative, we need to increase it.
            return abs(x) + 1.0
    elif target == "negative":
        if x < 0:
            return 0
        else:
            # Distance to make x < 0. If x is 0 or positive, we need to decrease it.
            return abs(x) + 1.0
    elif target == "zero":
        if x == 0:
            return 0
        else:
            # Distance to make x == 0
            return abs(x)
    else:
        raise ValueError(f"Unknown target: {target}")

# ================================================================================
# Original function: string_category
# Fitness function: fitness_string_category
# LLM targets: ['empty', 'long_palindrome', 'short_palindrome', 'long_non_palindrome', 'other']
# Notes: Corrected the branch distance calculations for 'less than or equal to' conditions (e.g., len(s) <= 3 and len(s) <= 5) by introducing 'le_dist' helper function. Previously, the negation of 'greater than' was incorrectly using 'ge_dist' with inverted logic, leading to semantic mismatches.
# ================================================================================

TARGETS_string_category = ["empty", "long_palindrome", "short_palindrome", "long_non_palindrome", "other"]

def fitness_string_category(chromosome, target):
    s = chromosome[0]
    s_rev = s[::-1]
    len_s = len(s)

    # Helper functions for branch distance calculations
    def eq_dist(val, target_val):
        return abs(val - target_val)

    def gt_dist(val, threshold):
        # Distance to satisfy val > threshold (i.e., val >= threshold + 1)
        return max(0, (threshold + 1) - val)

    def ge_dist(val, threshold):
        # Distance to satisfy val >= threshold
        return max(0, threshold - val)

    def lt_dist(val, threshold):
        # Distance to satisfy val < threshold (i.e., val <= threshold - 1)
        return max(0, val - (threshold - 1))

    def le_dist(val, threshold):
        # Distance to satisfy val <= threshold
        return max(0, val - threshold)

    def str_pal_dist(s_actual, s_reversed):
        # Distance to satisfy s_actual == s_reversed
        if s_actual == s_reversed:
            return 0
        mismatches = 0
        # s_actual and s_reversed always have the same length
        for i in range(len(s_actual)):
            if s_actual[i] != s_reversed[i]:
                mismatches += 1
        return mismatches if mismatches > 0 else 1

    # Branch distances for conditions and their negations
    dist_len_s_eq_0_true = eq_dist(len_s, 0)
    dist_len_s_ne_0_true = gt_dist(len_s, 0) # equivalent to len_s > 0 or len_s >= 1

    dist_s_is_palindrome_true = str_pal_dist(s, s_rev)
    dist_s_is_not_palindrome_true = 0 if s != s_rev else 1 # 0 if s is not a palindrome, 1 if it is

    dist_len_s_gt_3_true = gt_dist(len_s, 3) # len(s) > 3 means len(s) >= 4
    dist_len_s_le_3_true = le_dist(len_s, 3) # len(s) <= 3

    dist_len_s_gt_5_true = gt_dist(len_s, 5) # len(s) > 5 means len(s) >= 6
    dist_len_s_le_5_true = le_dist(len_s, 5) # len(s) <= 5

    if target == "empty":
        # Path: len(s) == 0
        return dist_len_s_eq_0_true
    elif target == "long_palindrome":
        # Path: len(s) != 0 AND s == s[::-1] AND len(s) > 3
        return dist_len_s_ne_0_true + dist_s_is_palindrome_true + dist_len_s_gt_3_true
    elif target == "short_palindrome":
        # Path: len(s) != 0 AND s == s[::-1] AND NOT (len(s) > 3) --> len(s) <= 3
        return dist_len_s_ne_0_true + dist_s_is_palindrome_true + dist_len_s_le_3_true
    elif target == "long_non_palindrome":
        # Path: len(s) != 0 AND s != s[::-1] AND len(s) > 5
        return dist_len_s_ne_0_true + dist_s_is_not_palindrome_true + dist_len_s_gt_5_true
    elif target == "other":
        # Path: len(s) != 0 AND s != s[::-1] AND NOT (len(s) > 5) --> len(s) <= 5
        return dist_len_s_ne_0_true + dist_s_is_not_palindrome_true + dist_len_s_le_5_true
    else:
        raise ValueError("Unknown target")

# ================================================================================
# Original function: triangle_type
# Fitness function: fitness_triangle_type
# LLM targets: ['invalid_side', 'not_triangle', 'equilateral', 'isosceles', 'scalene']
# Notes: The fitness function calculates branch distances for each condition in the `triangle_type` function. It accumulates these distances sequentially. For each conditional branch (if/elif), if the target is not within that branch, the fitness function adds the branch distance required to falsify the condition. Additionally, a constant penalty of `1.0` is added if the condition was actually met (meaning the program flow diverted from the intended path). This ensures that fitness is `0` only when the target path is fully covered, and positive otherwise, with smaller values indicating closer proximity to the target. The `max(0, ...)` ensures all distances are non-negative.
# ================================================================================

def fitness_triangle_type(chromosome, target):
    a, b, c = chromosome[0], chromosome[1], chromosome[2]

    current_fitness = 0.0

    # --- Branch 1: `if a <= 0 or b <= 0 or c <= 0:` returns "invalid_side" ---
    dist_a_le_0 = max(0, a)
    dist_b_le_0 = max(0, b)
    dist_c_le_0 = max(0, c)
    
    cond_invalid_side = (a <= 0 or b <= 0 or c <= 0)
    
    # Fitness to make `a <= 0 or b <= 0 or c <= 0` true
    fitness_to_invalid_side_true = min(dist_a_le_0, dist_b_le_0, dist_c_le_0)

    # Fitness to make `a <= 0 or b <= 0 or c <= 0` false (i.e., `a > 0 and b > 0 and c > 0`)
    fitness_to_invalid_side_false = max(0, -a) + max(0, -b) + max(0, -c)

    if target == "invalid_side":
        return fitness_to_invalid_side_true
    
    # If target is not "invalid_side", we must have avoided this branch.
    # Add fitness for avoiding it. Add 1.0 penalty if we failed to avoid it.
    current_fitness += fitness_to_invalid_side_false
    if cond_invalid_side:
        current_fitness += 1.0 # Penalty for entering this branch when we shouldn't have

    # --- Branch 2: `if a + b <= c or a + c <= b or b + c <= a:` returns "not_triangle" ---
    dist_ab_le_c = max(0, (a + b) - c)
    dist_ac_le_b = max(0, (a + c) - b)
    dist_bc_le_a = max(0, (b + c) - a)

    cond_not_triangle = (a + b <= c or a + c <= b or b + c <= a)
    
    # Fitness to make `a + b <= c or ...` true
    fitness_to_not_triangle_true = min(dist_ab_le_c, dist_ac_le_b, dist_bc_le_a)

    # Fitness to make `a + b <= c or ...` false (i.e., `a+b > c and a+c > b and b+c > a`)
    fitness_to_not_triangle_false = max(0, c - (a + b)) + max(0, b - (a + c)) + max(0, a - (b + c))

    if target == "not_triangle":
        return current_fitness + fitness_to_not_triangle_true
    
    # If target is not "not_triangle", we must have avoided this branch.
    current_fitness += fitness_to_not_triangle_false
    if cond_not_triangle:
        current_fitness += 1.0 # Penalty for entering this branch when we shouldn't have

    # --- Branch 3: `if a == b and b == c:` returns "equilateral" ---
    dist_a_eq_b = abs(a - b)
    dist_b_eq_c = abs(b - c)

    cond_equilateral = (a == b and b == c)

    # Fitness to make `a == b and b == c` true
    fitness_to_equilateral_true = dist_a_eq_b + dist_b_eq_c

    # Fitness to make `a == b and b == c` false (i.e., `a != b or b != c`)
    # The distance to make 'X != Y' true is 0 if X != Y, and 1 if X == Y.
    fitness_to_equilateral_false = min((1.0 if a == b else 0.0), (1.0 if b == c else 0.0))

    if target == "equilateral":
        return current_fitness + fitness_to_equilateral_true
    
    # If target is not "equilateral", we must have avoided this branch.
    current_fitness += fitness_to_equilateral_false
    if cond_equilateral:
        current_fitness += 1.0 # Penalty for entering this branch when we shouldn't have

    # --- Branch 4: `elif a == b or a == c or b == c:` returns "isosceles" ---
    dist_a_eq_b_iso = abs(a - b)
    dist_a_eq_c_iso = abs(a - c)
    dist_b_eq_c_iso = abs(b - c)

    cond_isosceles = (a == b or a == c or b == c)

    # Fitness to make `a == b or a == c or b == c` true
    fitness_to_isosceles_true = min(dist_a_eq_b_iso, dist_a_eq_c_iso, dist_b_eq_c_iso)

    # Fitness to make `a == b or a == c or b == c` false (i.e., `a != b and a != c and b != c`)
    # Distance to make `X != Y` true: 0 if X != Y, 1 if X == Y.
    fitness_to_isosceles_false = (1.0 if a == b else 0.0) + (1.0 if a == c else 0.0) + (1.0 if b == c else 0.0)

    if target == "isosceles":
        return current_fitness + fitness_to_isosceles_true
    
    # If target is not "isosceles", we must have avoided this branch.
    current_fitness += fitness_to_isosceles_false
    if cond_isosceles:
        current_fitness += 1.0 # Penalty for entering this branch when we shouldn't have

    # --- Branch 5: `else:` returns "scalene" ---
    if target == "scalene":
        # To reach scalene, all previous conditions must be false.
        # current_fitness already accumulates distances for avoiding previous branches.
        # The target "scalene" itself has no further explicit conditions to satisfy,
        # its 'fitness_true' is effectively 0 if its implicit conditions are met.
        # If we reached this point and the chromosome truly leads to scalene, current_fitness will be 0.
        return current_fitness
    
    raise ValueError("Unknown target: " + target)

# ================================================================================
# Original function: username_category
# Fitness function: fitness_username_category
# LLM targets: ['empty', 'too_short', 'starts_with_digit', 'strong_username', 'medium_username', 'weak_username']
# Notes: The fitness function calculates branch distances for each conditional statement along the execution path leading to the target return value. For boolean conditions, a distance of 0 is assigned if the condition is met and 1 otherwise. For numeric comparisons, standard branch distance formulas (e.g., `abs(a-b)` for equality, `max(0, a-b+1)` for `a < b`) are used. Distances are summed along the required path. For 'NOT (A and B and C and D)' type conditions, the fitness is calculated as the minimum of the fitnesses to make 'not A', 'not B', 'not C', or 'not D' true.
# ================================================================================

def _distance_eq(left, right):
    return abs(left - right)

def _distance_ne(left, right):
    return 0 if left != right else 1

def _distance_lt(left, right):
    return max(0, left - right + 1)

def _distance_le(left, right):
    return max(0, left - right)

def _distance_gt(left, right):
    return max(0, right - left + 1)

def _distance_ge(left, right):
    return max(0, right - left)

def _boolean_distance(condition):
    return 0 if condition else 1


TARGETS_username_category = ["empty", "too_short", "starts_with_digit", "strong_username", "medium_username", "weak_username"]

def fitness_username_category(chromosome, target):
    username = chromosome[0]
    ulen = len(username)

    _has_digit = False
    _has_upper = False
    _has_special = False
    _first_char_is_digit = False
    _first_char_exists = ulen > 0

    if _first_char_exists:
        _first_char_is_digit = username[0].isdigit()

    for ch in username:
        if ch.isdigit():
            _has_digit = True
        if ch.isupper():
            _has_upper = True
        if not ch.isalnum():
            _has_special = True
    
    # Branch distances for character properties to be TRUE
    bd_has_digit_true = _boolean_distance(_has_digit)
    bd_has_upper_true = _boolean_distance(_has_upper)
    bd_has_special_true = _boolean_distance(_has_special)

    # Branch distances for character properties to be FALSE
    bd_has_digit_false = _boolean_distance(not _has_digit)
    bd_has_upper_false = _boolean_distance(not _has_upper)
    bd_has_special_false = _boolean_distance(not _has_special)


    if target == "empty":
        # Path conditions:
        # 1. len(username) == 0
        return _distance_eq(ulen, 0)

    elif target == "too_short":
        # Path conditions:
        # 1. len(username) != 0
        # 2. len(username) < 5
        return _distance_ne(ulen, 0) + _distance_lt(ulen, 5)

    elif target == "starts_with_digit":
        # Path conditions:
        # 1. len(username) != 0
        # 2. len(username) >= 5
        # 3. username[0].isdigit() (implies len(username) > 0)
        return (_distance_ne(ulen, 0) +
                _distance_ge(ulen, 5) +
                _boolean_distance(_first_char_is_digit))

    elif target == "strong_username":
        # Path conditions:
        # 1. len(username) != 0
        # 2. len(username) >= 5
        # 3. not username[0].isdigit() (implies len(username) > 0)
        # 4. len(username) >= 10
        # 5. has_digit
        # 6. has_upper
        # 7. has_special
        return (_distance_ne(ulen, 0) +
                _distance_ge(ulen, 5) +
                _boolean_distance(_first_char_exists and not _first_char_is_digit) +
                _distance_ge(ulen, 10) +
                bd_has_digit_true +
                bd_has_upper_true +
                bd_has_special_true)

    elif target == "medium_username":
        # Path conditions:
        # 1. len(username) != 0
        # 2. len(username) >= 5
        # 3. not username[0].isdigit()
        # 4. NOT (len(username) >= 10 and has_digit and has_upper and has_special)
        # 5. has_digit
        # 6. has_upper
        
        # Fitness for NOT (A and B and C and D) = min(fitness(not A), fitness(not B), fitness(not C), fitness(not D))
        d4_not_strong_cond = min(
            _distance_lt(ulen, 10),     # Not (len >= 10)
            bd_has_digit_false,        # Not (has_digit)
            bd_has_upper_false,        # Not (has_upper)
            bd_has_special_false       # Not (has_special)
        )
        
        return (_distance_ne(ulen, 0) +
                _distance_ge(ulen, 5) +
                _boolean_distance(_first_char_exists and not _first_char_is_digit) +
                d4_not_strong_cond +
                bd_has_digit_true +
                bd_has_upper_true)

    elif target == "weak_username":
        # Path conditions:
        # 1. len(username) != 0
        # 2. len(username) >= 5
        # 3. not username[0].isdigit()
        # 4. NOT (len(username) >= 10 and has_digit and has_upper and has_special)
        # 5. NOT (has_digit and has_upper)

        d4_not_strong_cond = min(
            _distance_lt(ulen, 10),
            bd_has_digit_false,
            bd_has_upper_false,
            bd_has_special_false
        )

        # Fitness for NOT (A and B) = min(fitness(not A), fitness(not B))
        d5_not_medium_cond = min(
            bd_has_digit_false,
            bd_has_upper_false
        )

        return (_distance_ne(ulen, 0) +
                _distance_ge(ulen, 5) +
                _boolean_distance(_first_char_exists and not _first_char_is_digit) +
                d4_not_strong_cond +
                d5_not_medium_cond)

    else:
        raise ValueError(f"Unknown target: {target}")

# ================================================================================
# Unified fitness interface
# ================================================================================

def evaluate_fitness(function_name, chromosome, target):
    if function_name == 'bmi_category':
        return fitness_bmi_category(chromosome, target)
    elif function_name == 'list_pattern':
        return fitness_list_pattern(chromosome, target)
    elif function_name == 'number_kind':
        return fitness_number_kind(chromosome, target)
    elif function_name == 'password_strength':
        return fitness_password_strength(chromosome, target)
    elif function_name == 'pin_pattern':
        return fitness_pin_pattern(chromosome, target)
    elif function_name == 'shipping_discount':
        return fitness_shipping_discount(chromosome, target)
    elif function_name == 'sign_type':
        return fitness_sign_type(chromosome, target)
    elif function_name == 'string_category':
        return fitness_string_category(chromosome, target)
    elif function_name == 'triangle_type':
        return fitness_triangle_type(chromosome, target)
    elif function_name == 'username_category':
        return fitness_username_category(chromosome, target)
    else:
        raise ValueError(f'Unknown function name: {function_name}')
