

import ast
from pathlib import Path

import pandas as pd


RESULTS_FILE = "results/all_methods_results.csv"
OUTPUT_TEST_FILE = "tests/test_llm_generated_cases.py"


METHOD_PRIORITY = {
    "GA_ADAPTIVE": 0,
    "GA_FIXED": 1,
    "HILL_CLIMBING": 2,
    "RANDOM": 3,
}


def parse_chromosome(value):


    if isinstance(value, list):
        return value

    return ast.literal_eval(str(value))


def main():
    df = pd.read_csv(RESULTS_FILE)

    df["found"] = df["found"].astype(str).str.lower() == "true"
    df["validated"] = df["validated"].astype(str).str.lower() == "true"

    df["best_fitness"] = pd.to_numeric(df["best_fitness"], errors="coerce")
    df["generation"] = pd.to_numeric(df["generation"], errors="coerce")
    df["evaluations"] = pd.to_numeric(df["evaluations"], errors="coerce")
    df["runtime"] = pd.to_numeric(df["runtime"], errors="coerce")

    df["method_priority"] = df["method"].map(METHOD_PRIORITY).fillna(99)

    df = df[
        (df["found"] == True)
        & (df["validated"] == True)
        & (df["best_fitness"] == 0)
    ].copy()

    if df.empty:
        raise ValueError(
            "No successful validated test cases found. "
            "Run random_baseline.py, hill_climbing.py, ga_comparison.py, "
            "and compare_all_methods.py first."
        )

    df = df.sort_values(
        by=[
            "function_name",
            "target",
            "method_priority",
            "evaluations",
            "runtime",
        ]
    )

    selected = df.drop_duplicates(
        subset=["function_name", "target"],
        keep="first",
    )

    output_path = Path(OUTPUT_TEST_FILE)
    output_path.parent.mkdir(exist_ok=True)

    with output_path.open("w", encoding="utf-8") as file:
        file.write("# tests/test_llm_generated_cases.py\n")
        file.write("# This file was generated by generate_pytest_cases.py\n")
        file.write("# Test cases were selected from results/all_methods_results.csv\n\n")

        file.write("import pytest\n\n")
        file.write("from target_functions import (\n")
        file.write("    sign_type,\n")
        file.write("    number_kind,\n")
        file.write("    max_of_three,\n")
        file.write("    triangle_type,\n")
        file.write("    is_leap_year,\n")
        file.write("    grade_category,\n")
        file.write("    bmi_category,\n")
        file.write("    loan_eligibility,\n")
        file.write("    password_strength,\n")
        file.write("    string_category,\n")
        file.write("    list_score,\n")
        file.write("    list_pattern,\n")
        file.write(")\n")
        file.write("from validation import validate_branch, get_reached_branch\n\n")

        file.write("FUNCTIONS = {\n")
        file.write("    'sign_type': sign_type,\n")
        file.write("    'number_kind': number_kind,\n")
        file.write("    'max_of_three': max_of_three,\n")
        file.write("    'triangle_type': triangle_type,\n")
        file.write("    'is_leap_year': is_leap_year,\n")
        file.write("    'grade_category': grade_category,\n")
        file.write("    'bmi_category': bmi_category,\n")
        file.write("    'loan_eligibility': loan_eligibility,\n")
        file.write("    'password_strength': password_strength,\n")
        file.write("    'string_category': string_category,\n")
        file.write("    'list_score': list_score,\n")
        file.write("    'list_pattern': list_pattern,\n")
        file.write("}\n\n")

        file.write("# Each tuple is:\n")
        file.write("# function_name, target, chromosome, method_used\n")
        file.write("TEST_CASES = [\n")

        for _, row in selected.iterrows():
            function_name = row["function_name"]
            target = row["target"]
            chromosome = parse_chromosome(row["best_chromosome"])
            method = row["method"]

            file.write(
                f"    ('{function_name}', '{target}', {repr(chromosome)}, '{method}'),\n"
            )

        file.write("]\n\n")

        file.write("@pytest.mark.parametrize(\n")
        file.write("    'function_name, target, chromosome, method_used',\n")
        file.write("    TEST_CASES,\n")
        file.write(")\n")
        file.write("def test_llm_generated_input_covers_target(function_name, target, chromosome, method_used):\n")
        file.write("    target_function = FUNCTIONS[function_name]\n")
        file.write("    output = target_function(*chromosome)\n")
        file.write("    assert output == target\n")
        file.write("    assert validate_branch(function_name, chromosome, target)\n")
        file.write("    assert get_reached_branch(function_name, chromosome) == target\n")

    print(f"Generated pytest file: {OUTPUT_TEST_FILE}")
    print(f"Number of generated test cases: {len(selected)}")

    expected_targets = 51

    if len(selected) < expected_targets:
        print(
            f"WARNING: Expected {expected_targets} test cases, "
            f"but generated only {len(selected)}."
        )
        print("Some target branches may not have successful validated inputs.")

    print("\nSelected test cases:")
    for _, row in selected.iterrows():
        print(
            row["function_name"],
            row["target"],
            row["best_chromosome"],
            "method=" + str(row["method"]),
        )


if __name__ == "__main__":
    main()