# generated_fitness.py
# This file was generated by generate_fitness_zero_shot.py
# Zero-shot source-code-only LLM fitness generation.

# ================================================================================
# Original function: sign_type
# Fitness function: fitness_sign_type
# Targets inferred by LLM: ['positive', 'negative', 'zero']
# Notes: The fitness function aims to achieve branch coverage for 'positive', 'negative', and 'zero' outcomes. For 'positive' (x > 0), fitness is 0 if x is positive, otherwise it's (1 - x). For 'negative' (x < 0), fitness is 0 if x is negative, otherwise it's (1 + x). For 'zero' (x == 0), fitness is 0 if x is zero, otherwise it's abs(x).
# ================================================================================

def fitness_sign_type(chromosome, target):
    x = chromosome[0]
    if target == "positive":
        if x > 0:
            return 0
        else:
            return 1 - x
    elif target == "negative":
        if x < 0:
            return 0
        else:
            return 1 + x
    elif target == "zero":
        if x == 0:
            return 0
        else:
            return abs(x)
    else:
        raise ValueError("Unknown target branch")

# ================================================================================
# Original function: number_kind
# Fitness function: fitness_number_kind
# Targets inferred by LLM: ['zero', 'even', 'odd']
# Notes: The fitness function calculates a sum of 'distances' for each condition required to reach a specific target branch. For 'zero', it aims for x to be 0. For 'even', it aims for x to be non-zero and even. For 'odd', it aims for x to be non-zero and odd. Each distance component is 0 if the condition is met and positive otherwise.
# ================================================================================

def fitness_number_kind(chromosome, target):
    x = chromosome[0]

    f_x_eq_0 = abs(x - 0)
    f_x_ne_0 = 1 if x == 0 else 0
    f_x_is_even = abs(x % 2)
    f_x_is_odd = 1 - abs(x % 2)

    if target == "zero":
        return f_x_eq_0
    elif target == "even":
        return f_x_ne_0 + f_x_is_even
    elif target == "odd":
        return f_x_ne_0 + f_x_is_odd
    else:
        return float('inf')

# ================================================================================
# Original function: max_of_three
# Fitness function: fitness_max_of_three
# Targets inferred by LLM: ['a_is_max', 'b_is_max', 'c_is_max']
# Notes: The fitness function uses an approach level strategy, calculating the sum or minimum of distances for each predicate to be true or false as required for a specific branch. 'dist_ge' calculates the distance for a 'greater than or equal to' condition to be met, and 'dist_lt' for a 'less than' condition. A distance of 0 indicates the condition is met, while positive values indicate how far it is from being met.
# ================================================================================

def fitness_max_of_three(chromosome, target):
    a, b, c = chromosome

    def dist_ge(val1, val2):
        if val1 >= val2:
            return 0
        else:
            return val2 - val1 + 1

    def dist_lt(val1, val2):
        if val1 < val2:
            return 0
        else:
            return val1 - val2 + 1

    if target == "a_is_max":
        # Target: a >= b AND a >= c
        fitness = dist_ge(a, b) + dist_ge(a, c)
        return fitness

    elif target == "b_is_max":
        # Target: NOT (a >= b AND a >= c) AND (b >= a AND b >= c)
        # Which simplifies to: (a < b OR a < c) AND (b >= a AND b >= c)

        # Fitness for failing the first 'if' condition (a < b OR a < c)
        fail_first_if_fitness = min(dist_lt(a, b), dist_lt(a, c))

        # Fitness for satisfying the 'elif' condition (b >= a AND b >= c)
        satisfy_elif_fitness = dist_ge(b, a) + dist_ge(b, c)

        fitness = fail_first_if_fitness + satisfy_elif_fitness
        return fitness

    elif target == "c_is_max":
        # Target: NOT (a >= b AND a >= c) AND NOT (b >= a AND b >= c)
        # Which simplifies to: (a < b OR a < c) AND (b < a OR b < c)

        # Fitness for failing the first 'if' condition (a < b OR a < c)
        fail_first_if_fitness = min(dist_lt(a, b), dist_lt(a, c))

        # Fitness for failing the 'elif' condition (b < a OR b < c)
        fail_elif_fitness = min(dist_lt(b, a), dist_lt(b, c))

        fitness = fail_first_if_fitness + fail_elif_fitness
        return fitness
    
    return float('inf')

# ================================================================================
# Original function: triangle_type
# Fitness function: fitness_triangle_type
# Targets inferred by LLM: ['invalid_side', 'not_triangle', 'equilateral', 'isosceles', 'scalene']
# Notes: The fitness function calculates the branch distance for each target. It accumulates fitness from sequential preconditions, ensuring that for a specific target, all prior conditions that lead to that target's evaluation are met. A fitness of 0 means the target branch is covered, while a positive value indicates the distance to covering it, with higher values meaning further away. Helper functions `d_le`, `d_gt`, `d_eq`, and `d_ne` are used for specific comparison types.
# ================================================================================

def fitness_triangle_type(chromosome, target):
    a, b, c = chromosome[0], chromosome[1], chromosome[2]

    def d_le(x, y):
        return 0 if x <= y else x - y

    def d_gt(x, y):
        return 0 if x > y else y - x + 1

    def d_eq(x, y):
        return abs(x - y)

    def d_ne(x, y):
        return 0 if x != y else 1

    fitness = 0

    if target == "invalid_side":
        fitness = min(d_le(a, 0), d_le(b, 0), d_le(c, 0))
        return fitness

    # Preconditions for all targets after "invalid_side": a > 0, b > 0, c > 0
    # Fitness to ensure a, b, c are all strictly positive (at least 1)
    pre_sides_positive = d_gt(a, 0) + d_gt(b, 0) + d_gt(c, 0)

    if target == "not_triangle":
        # Target: a + b <= c or a + c <= b or b + c <= a
        # Preconditions: a > 0, b > 0, c > 0
        main_condition_fitness = min(d_le(a + b, c), d_le(a + c, b), d_le(b + c, a))
        fitness = pre_sides_positive + main_condition_fitness
        return fitness

    # Preconditions for all targets after "not_triangle": a,b,c form a valid triangle
    # Fitness to ensure a+b > c, a+c > b, b+c > a
    pre_is_triangle = d_gt(a + b, c) + d_gt(a + c, b) + d_gt(b + c, a)

    if target == "equilateral":
        # Target: a == b and b == c
        # Preconditions: a,b,c > 0 and forms a triangle
        main_condition_fitness = d_eq(a, b) + d_eq(b, c)
        fitness = pre_sides_positive + pre_is_triangle + main_condition_fitness
        return fitness

    # Preconditions for targets after "equilateral": not equilateral
    # Fitness to ensure not (a == b and b == c) i.e. (a != b or b != c)
    pre_not_equilateral = min(d_ne(a, b), d_ne(b, c))

    if target == "isosceles":
        # Target: a == b or a == c or b == c
        # Preconditions: a,b,c > 0, forms a triangle, not equilateral
        main_condition_fitness = min(d_eq(a, b), d_eq(a, c), d_eq(b, c))
        fitness = pre_sides_positive + pre_is_triangle + pre_not_equilateral + main_condition_fitness
        return fitness

    if target == "scalene":
        # Target: not (a == b or a == c or b == c) i.e. a != b and a != c and b != c
        # Preconditions: a,b,c > 0, forms a triangle, not isosceles (implies not equilateral)
        main_condition_fitness = d_ne(a, b) + d_ne(a, c) + d_ne(b, c)
        fitness = pre_sides_positive + pre_is_triangle + main_condition_fitness
        return fitness

    return float('inf')

# ================================================================================
# Original function: is_leap_year
# Fitness function: fitness_is_leap_year
# Targets inferred by LLM: ['divisible_by_400', 'divisible_by_100_not_400', 'divisible_by_4_not_100', 'not_leap_year']
# Notes: The fitness function `fitness_is_leap_year` takes a chromosome (a list containing one integer, `year`) and a target branch name. It calculates a fitness score for reaching the specified target. For conditions requiring divisibility (e.g., `year % N == 0`), the fitness contribution is `abs(year % N)`. For conditions requiring non-divisibility (e.g., `year % N != 0`), a penalty of `1` is added if the number *is* divisible by `N`. The total fitness is the sum of these individual condition fitnesses. A fitness of `0` indicates the target branch has been covered.
# ================================================================================

def fitness_is_leap_year(chromosome, target):
    year = chromosome[0]

    # Target: "divisible_by_400" (if year % 400 == 0)
    if target == "divisible_by_400":
        if year % 400 == 0:
            return 0
        else:
            return abs(year % 400)

    # Target: "divisible_by_100_not_400" (elif year % 100 == 0)
    # Conditions: year % 400 != 0 AND year % 100 == 0
    if target == "divisible_by_100_not_400":
        fitness = 0
        # Condition 1: year % 400 != 0
        if year % 400 == 0:
            fitness += 1
        
        # Condition 2: year % 100 == 0
        if year % 100 != 0:
            fitness += abs(year % 100)
            
        return fitness

    # Target: "divisible_by_4_not_100" (elif year % 4 == 0)
    # Conditions: year % 400 != 0 AND year % 100 != 0 AND year % 4 == 0
    if target == "divisible_by_4_not_100":
        fitness = 0
        # Condition 1: year % 400 != 0
        if year % 400 == 0:
            fitness += 1
        
        # Condition 2: year % 100 != 0
        if year % 100 == 0:
            fitness += 1
            
        # Condition 3: year % 4 == 0
        if year % 4 != 0:
            fitness += abs(year % 4)
            
        return fitness

    # Target: "not_leap_year" (else branch)
    # Conditions: year % 400 != 0 AND year % 100 != 0 AND year % 4 != 0
    if target == "not_leap_year":
        fitness = 0
        # Condition 1: year % 400 != 0
        if year % 400 == 0:
            fitness += 1
        
        # Condition 2: year % 100 != 0
        if year % 100 == 0:
            fitness += 1
            
        # Condition 3: year % 4 != 0
        if year % 4 == 0:
            fitness += 1
            
        return fitness
    
    return float('inf')

# ================================================================================
# Original function: grade_category
# Fitness function: fitness_grade_category
# Targets inferred by LLM: ['invalid', 'A', 'B', 'C', 'D', 'F']
# Notes: The fitness function uses branch distance (calculated with helper functions bd_gt, bd_ge, bd_lt, bd_le) for each condition. For 'OR' conditions, it takes the minimum of individual branch distances. For 'AND' conditions and sequentially evaluated 'elif' branches, it sums the branch distances of all required conditions and their preceding negations. A constant of 1 is added to the branch distance if a condition is not met, ensuring a positive fitness value when the target is not covered and a zero value when covered. Each subsequent 'elif' target adds the branch distance for making the preceding conditions false to its overall fitness calculation.
# ================================================================================

def fitness_grade_category(chromosome, target):
    score = chromosome[0]

    def bd_gt(a, b):
        return 0 if a > b else b - a + 1

    def bd_ge(a, b):
        return 0 if a >= b else b - a + 1

    def bd_lt(a, b):
        return 0 if a < b else a - b + 1

    def bd_le(a, b):
        return 0 if a <= b else a - b + 1

    if target == "invalid":
        fitness_lt_0 = bd_lt(score, 0)
        fitness_gt_100 = bd_gt(score, 100)
        return min(fitness_lt_0, fitness_gt_100)

    pre_fitness_valid_range = bd_ge(score, 0) + bd_le(score, 100)

    if target == "A":
        return pre_fitness_valid_range + bd_ge(score, 90)

    pre_fitness_lt_90 = bd_lt(score, 90)
    pre_fitness_A_false = pre_fitness_valid_range + pre_fitness_lt_90

    if target == "B":
        return pre_fitness_A_false + bd_ge(score, 80)

    pre_fitness_lt_80 = bd_lt(score, 80)
    pre_fitness_B_false = pre_fitness_A_false + pre_fitness_lt_80

    if target == "C":
        return pre_fitness_B_false + bd_ge(score, 70)

    pre_fitness_lt_70 = bd_lt(score, 70)
    pre_fitness_C_false = pre_fitness_B_false + pre_fitness_lt_70

    if target == "D":
        return pre_fitness_C_false + bd_ge(score, 60)

    pre_fitness_lt_60 = bd_lt(score, 60)
    pre_fitness_D_false = pre_fitness_C_false + pre_fitness_lt_60

    if target == "F":
        return pre_fitness_D_false
    
    return float('inf')

# ================================================================================
# Original function: bmi_category
# Fitness function: fitness_bmi_category
# Targets inferred by LLM: ['invalid_height', 'underweight', 'normal', 'overweight', 'obese']
# Notes: A fitness function to guide the search towards different BMI categories, including an invalid height scenario. It calculates branch distances based on the conditions for each category. For targets requiring a positive height, it prioritizes achieving a valid height before evaluating BMI-related conditions.
# ================================================================================

def fitness_bmi_category(chromosome, target):
    weight = chromosome[0]
    height = chromosome[1]

    if target == "invalid_height":
        # Target: height <= 0
        if height <= 0:
            return 0
        else:
            # Penalize by how far height is from being non-positive
            # If height is 1, fitness is 1. If height is 0.01, fitness is 0.01.
            return height

    # For all other targets, height must be positive.
    # Calculate a fitness component for ensuring height is positive.
    # If height is negative or zero, this will be positive.
    # If height is e.g., 0.1, then -0.1 + 1 = 0.9. If height is 1, then -1 + 1 = 0.
    fitness_height_positive_component = max(0, -height + 1)
    
    # If height is not positive enough, we prioritize fixing height.
    if fitness_height_positive_component > 0:
        return fitness_height_positive_component

    # Now we are sure height > 0, so BMI calculation is safe.
    bmi = weight / (height * height)

    if target == "underweight":
        # Target: bmi < 18.5
        # If bmi < 18.5, fitness_bmi_underweight = 0
        # Else (bmi >= 18.5), fitness_bmi_underweight = bmi - 18.5
        fitness_bmi_underweight = max(0, bmi - 18.5)
        return fitness_bmi_underweight

    elif target == "normal":
        # Target: 18.5 <= bmi < 25
        # Component 1: bmi >= 18.5 (i.e., not bmi < 18.5)
        # If bmi < 18.5, fitness_normal_lower = 18.5 - bmi
        # Else (bmi >= 18.5), fitness_normal_lower = 0
        fitness_normal_lower = max(0, 18.5 - bmi)

        # Component 2: bmi < 25 (i.e., not bmi >= 25)
        # If bmi >= 25, fitness_normal_upper = bmi - 25
        # Else (bmi < 25), fitness_normal_upper = 0
        fitness_normal_upper = max(0, bmi - 25)
        
        return fitness_normal_lower + fitness_normal_upper

    elif target == "overweight":
        # Target: 25 <= bmi < 30
        # Component 1: bmi >= 25 (i.e., not bmi < 25)
        fitness_overweight_lower = max(0, 25 - bmi)

        # Component 2: bmi < 30 (i.e., not bmi >= 30)
        fitness_overweight_upper = max(0, bmi - 30)
        
        return fitness_overweight_lower + fitness_overweight_upper

    elif target == "obese":
        # Target: bmi >= 30 (i.e., not bmi < 30)
        # If bmi < 30, fitness_bmi_obese = 30 - bmi
        # Else (bmi >= 30), fitness_bmi_obese = 0
        fitness_bmi_obese = max(0, 30 - bmi)
        return fitness_bmi_obese
    
    # Fallback in case of an unhandled target
    return float('inf')

# ================================================================================
# Original function: loan_eligibility
# Fitness function: fitness_loan_eligibility
# Targets inferred by LLM: ['reject_underage', 'approve', 'review', 'reject_low_income']
# Notes: Generates a fitness function that calculates the branch distance to cover specific return paths in the loan_eligibility function. It uses arithmetic distances for numeric comparisons and 0/1 for boolean conditions, summing these to provide an overall fitness score. The 'min' function is used for 'OR' conditions in path constraints.
# ================================================================================

def fitness_loan_eligibility(chromosome, target):
    age, income, employed = chromosome

    dist_age_lt_18 = max(0, age - 18 + 1)
    dist_age_ge_18 = max(0, 18 - age)

    dist_income_ge_50000 = max(0, 50000 - income)
    dist_income_lt_50000 = max(0, income - 50000 + 1)

    dist_income_ge_30000 = max(0, 30000 - income)
    dist_income_lt_30000 = max(0, income - 30000 + 1)

    dist_employed_true = 0 if employed else 1
    dist_employed_false = 0 if not employed else 1

    if target == "reject_underage":
        return dist_age_lt_18

    if target == "approve":
        return dist_age_ge_18 + dist_income_ge_50000 + dist_employed_true

    if target == "review":
        fitness_preconditions = dist_age_ge_18
        fitness_avoid_approve = min(dist_income_lt_50000, dist_employed_false)
        fitness_condition = dist_income_ge_30000
        return fitness_preconditions + fitness_avoid_approve + fitness_condition

    if target == "reject_low_income":
        fitness_preconditions = dist_age_ge_18
        fitness_avoid_approve = min(dist_income_lt_50000, dist_employed_false)
        fitness_avoid_review = dist_income_lt_30000
        return fitness_preconditions + fitness_avoid_approve + fitness_avoid_review

    return float('inf')

# ================================================================================
# Original function: password_strength
# Fitness function: fitness_password_strength
# Targets inferred by LLM: ['weak_short', 'strong', 'medium', 'weak_no_digit_upper']
# Notes: Fitness function calculates branch distance for different password strength categories ('weak_short', 'strong', 'medium', 'weak_no_digit_upper') based on length and presence of digits/uppercase characters in the input string.
# ================================================================================

def fitness_password_strength(chromosome, target):
    s = chromosome[0]
    len_s = len(s)
    has_digit = any(ch.isdigit() for ch in s)
    has_upper = any(ch.isupper() for ch in s)
    has_digit_int = 1 if has_digit else 0
    has_upper_int = 1 if has_upper else 0

    if target == "weak_short":
        return max(0, len_s - 5)
    elif target == "strong":
        fitness = 0
        fitness += max(0, 10 - len_s)
        fitness += (1 - has_digit_int)
        fitness += (1 - has_upper_int)
        return fitness
    elif target == "medium":
        fitness = 0
        fitness += max(0, 6 - len_s)
        if not (has_digit or has_upper):
            fitness += 1
        if len_s >= 10 and has_digit and has_upper:
            fitness += 1
        return fitness
    elif target == "weak_no_digit_upper":
        fitness = 0
        fitness += max(0, 6 - len_s)
        if has_digit:
            fitness += 1
        if has_upper:
            fitness += 1
        return fitness
    return float('inf')

# ================================================================================
# Original function: string_category
# Fitness function: fitness_string_category
# Targets inferred by LLM: ['empty', 'long_palindrome', 'short_palindrome', 'long_non_palindrome', 'other']
# Notes: The fitness function calculates the sum of branch distances for reaching a specific target path. Each branch distance is 0 if the condition is met and a positive value otherwise, encouraging the search to satisfy the required conditions and bypass preceding branches. For 'NOT' conditions (i.e., previous 'elif' branches not taken), the fitness contributes 0 if the condition is successfully avoided and a positive value if it's unintentionally met.
# ================================================================================

def fitness_string_category(chromosome, target):
    s = chromosome[0]
    current_len = len(s)

    is_palindrome = (s == s[::-1])

    # Branch distances for individual positive conditions (0 if condition met, >0 otherwise)
    bd_len_eq_0 = abs(current_len - 0)
    bd_s_is_palindrome = 0 if is_palindrome else 1
    bd_len_gt_3 = max(0, 3 - current_len + 1)
    bd_len_gt_5 = max(0, 5 - current_len + 1)

    # Branch distances for individual negative conditions or 'not met' conditions (0 if condition *not* met, >0 otherwise)
    bd_len_ne_0 = 1 if current_len == 0 else 0
    bd_s_is_not_palindrome = 0 if not is_palindrome else 1
    bd_len_le_3 = max(0, current_len - 3)
    bd_len_le_5 = max(0, current_len - 5)

    if target == "empty":
        # Path: len(s) == 0
        return bd_len_eq_0

    elif target == "long_palindrome":
        # Path: (len(s) != 0) AND (s == s[::-1]) AND (len(s) > 3)
        return bd_len_ne_0 + bd_s_is_palindrome + bd_len_gt_3

    elif target == "short_palindrome":
        # Path: (len(s) != 0) AND NOT (s == s[::-1] and len(s) > 3) AND (s == s[::-1])
        # NOT (s == s[::-1] and len(s) > 3) simplifies to (s != s[::-1] OR len(s) <= 3)
        bd_not_second_elif_cond = min(bd_s_is_not_palindrome, bd_len_le_3)
        return bd_len_ne_0 + bd_not_second_elif_cond + bd_s_is_palindrome

    elif target == "long_non_palindrome":
        # Path: (len(s) != 0) AND NOT (s == s[::-1] and len(s) > 3) AND NOT (s == s[::-1]) AND (len(s) > 5)
        # NOT (s == s[::-1]) simplifies to (s != s[::-1])
        bd_not_second_elif_cond = min(bd_s_is_not_palindrome, bd_len_le_3)
        return bd_len_ne_0 + bd_not_second_elif_cond + bd_s_is_not_palindrome + bd_len_gt_5

    elif target == "other":
        # Path: (len(s) != 0) AND NOT (s == s[::-1] and len(s) > 3) AND NOT (s == s[::-1]) AND NOT (len(s) > 5)
        # NOT (s == s[::-1]) simplifies to (s != s[::-1])
        # NOT (len(s) > 5) simplifies to (len(s) <= 5)
        bd_not_second_elif_cond = min(bd_s_is_not_palindrome, bd_len_le_3)
        return bd_len_ne_0 + bd_not_second_elif_cond + bd_s_is_not_palindrome + bd_len_le_5

    return 1000

# ================================================================================
# Original function: list_score
# Fitness function: fitness_list_score
# Targets inferred by LLM: ['empty', 'high', 'medium', 'low']
# Notes: Generates fitness values for achieving specific return branches of 'list_score': 'empty' (list length is 0), 'high' (average > 10), 'medium' (average is between 0 and 10 inclusive), and 'low' (average < 0). Fitness is 0 if the target is met, otherwise a positive value representing the distance to satisfy the branch conditions.
# ================================================================================

def fitness_list_score(chromosome, target):
    nums = chromosome[0]
    length_nums = len(nums)

    if target == "empty":
        if length_nums == 0:
            return 0
        else:
            return float(length_nums)

    # For targets requiring calculations involving average, the list must not be empty
    if length_nums == 0:
        return 1.0 # Penalize for an empty list when other targets require a non-empty list

    total = sum(nums)
    avg = float(total) / length_nums

    if target == "high": # Condition: avg > 10
        if avg > 10:
            return 0
        else:
            # Distance for avg <= 10. We want avg to be greater than 10.
            return (10 - avg) + 1e-6

    elif target == "medium": # Condition: 0 <= avg <= 10
        if 0 <= avg <= 10:
            return 0
        else:
            fitness = 0.0
            # If avg is too high, push it down towards 10.
            if avg > 10:
                fitness += (avg - 10) + 1e-6
            # If avg is too low, push it up towards 0.
            if avg < 0:
                fitness += (0 - avg) + 1e-6
            return fitness

    elif target == "low": # Condition: avg < 0
        if avg < 0:
            return 0
        else:
            # Distance for avg >= 0. We want avg to be less than 0.
            return (avg - 0) + 1e-6

    return float('inf')

# ================================================================================
# Original function: list_pattern
# Fitness function: fitness_list_pattern
# Targets inferred by LLM: ['too_short', 'sorted_with_duplicates', 'sorted_unique', 'unsorted_with_duplicates', 'unsorted_unique']
# Notes: The fitness function `fitness_list_pattern` calculates a score for how far the input `nums` (from `chromosome[0]`) is from achieving a specific target branch. It breaks down the conditions of each branch (length, sortedness, presence of duplicates) into individual fitness components. For each component, a score of 0 indicates the condition is met, and a positive score indicates it is not met, with larger scores for greater deviation. These component scores are summed to give the total fitness for a given target. For the 'too_short' target, fitness is 0 if `len(nums)` is 0 or 1, and positive otherwise. For all other targets, fitness components ensure `len(nums) >= 2` is met, along with specific sortedness and duplicate conditions.
# ================================================================================

def fitness_list_pattern(chromosome, target):
    nums = chromosome[0]

    L = len(nums)
    is_nums_sorted = (nums == sorted(nums))
    
    # Calculate if there are duplicates by comparing list length to set length
    # Note: L - len(set(nums)) > 0 means there are duplicates
    #       L - len(set(nums)) == 0 means all elements are unique
    has_duplicates = (L != len(set(nums)))

    # Fitness component for len(nums) >= 2. 0 if met, positive otherwise.
    fitness_len_geq_2 = max(0, 2 - L)

    # Fitness component for nums == sorted(nums). 0 if sorted, positive otherwise.
    fitness_is_sorted = 1 if not is_nums_sorted else 0
    # Fitness component for nums != sorted(nums). 0 if unsorted, positive otherwise.
    fitness_is_unsorted = 1 if is_nums_sorted else 0

    # Fitness component for having duplicates. 0 if has duplicates, positive otherwise.
    fitness_has_duplicates = 1 if not has_duplicates else 0
    # Fitness component for having no duplicates. 0 if no duplicates, positive otherwise.
    fitness_no_duplicates = 1 if has_duplicates else 0

    if target == "too_short":
        # Target: len(nums) < 2
        # Fitness is 0 if len(nums) is 0 or 1. Positive if len(nums) >= 2.
        return max(0, L - 1)

    elif target == "sorted_with_duplicates":
        # Target: len(nums) >= 2 AND nums == sorted(nums) AND has_duplicates
        return fitness_len_geq_2 + fitness_is_sorted + fitness_has_duplicates

    elif target == "sorted_unique":
        # Target: len(nums) >= 2 AND nums == sorted(nums) AND not has_duplicates
        return fitness_len_geq_2 + fitness_is_sorted + fitness_no_duplicates

    elif target == "unsorted_with_duplicates":
        # Target: len(nums) >= 2 AND nums != sorted(nums) AND has_duplicates
        return fitness_len_geq_2 + fitness_is_unsorted + fitness_has_duplicates

    elif target == "unsorted_unique":
        # Target: len(nums) >= 2 AND nums != sorted(nums) AND not has_duplicates
        return fitness_len_geq_2 + fitness_is_unsorted + fitness_no_duplicates
    
    return float('inf')

# ================================================================================
# Unified fitness interface
# ================================================================================

def evaluate_fitness(function_name, chromosome, target):
    if function_name == 'sign_type':
        return fitness_sign_type(chromosome, target)
    elif function_name == 'number_kind':
        return fitness_number_kind(chromosome, target)
    elif function_name == 'max_of_three':
        return fitness_max_of_three(chromosome, target)
    elif function_name == 'triangle_type':
        return fitness_triangle_type(chromosome, target)
    elif function_name == 'is_leap_year':
        return fitness_is_leap_year(chromosome, target)
    elif function_name == 'grade_category':
        return fitness_grade_category(chromosome, target)
    elif function_name == 'bmi_category':
        return fitness_bmi_category(chromosome, target)
    elif function_name == 'loan_eligibility':
        return fitness_loan_eligibility(chromosome, target)
    elif function_name == 'password_strength':
        return fitness_password_strength(chromosome, target)
    elif function_name == 'string_category':
        return fitness_string_category(chromosome, target)
    elif function_name == 'list_score':
        return fitness_list_score(chromosome, target)
    elif function_name == 'list_pattern':
        return fitness_list_pattern(chromosome, target)
    else:
        raise ValueError(f'Unknown function name: {function_name}')
