# tests/test_llm_generated_cases.py
# This file was generated by generate_pytest_cases.py
# Test cases were selected from results/all_methods_results.csv

import pytest

from target_functions import (
    sign_type,
    number_kind,
    max_of_three,
    triangle_type,
    is_leap_year,
    grade_category,
    bmi_category,
    loan_eligibility,
    password_strength,
    string_category,
    list_score,
    list_pattern,
)
from validation import validate_branch, get_reached_branch

FUNCTIONS = {
    'sign_type': sign_type,
    'number_kind': number_kind,
    'max_of_three': max_of_three,
    'triangle_type': triangle_type,
    'is_leap_year': is_leap_year,
    'grade_category': grade_category,
    'bmi_category': bmi_category,
    'loan_eligibility': loan_eligibility,
    'password_strength': password_strength,
    'string_category': string_category,
    'list_score': list_score,
    'list_pattern': list_pattern,
}

# Each tuple is:
# function_name, target, chromosome, method_used
TEST_CASES = [
    ('bmi_category', 'invalid_height', [97.61706165444119, 0.0], 'GA_ADAPTIVE'),
    ('bmi_category', 'normal', [109.74835556970359, 2.1868421230572097], 'GA_ADAPTIVE'),
    ('bmi_category', 'obese', [143.38593538006737, 2.0585408665936304], 'GA_ADAPTIVE'),
    ('bmi_category', 'overweight', [82.55196659594584, 1.7381481042415983], 'GA_ADAPTIVE'),
    ('bmi_category', 'underweight', [51.32361457926732, 2.0576438002238877], 'GA_ADAPTIVE'),
    ('grade_category', 'A', [93], 'GA_ADAPTIVE'),
    ('grade_category', 'B', [82], 'GA_ADAPTIVE'),
    ('grade_category', 'C', [71], 'GA_ADAPTIVE'),
    ('grade_category', 'D', [61], 'GA_ADAPTIVE'),
    ('grade_category', 'F', [21], 'GA_ADAPTIVE'),
    ('grade_category', 'invalid', [-5], 'GA_ADAPTIVE'),
    ('is_leap_year', 'divisible_by_100_not_400', [1500], 'GA_ADAPTIVE'),
    ('is_leap_year', 'divisible_by_400', [1600], 'GA_ADAPTIVE'),
    ('is_leap_year', 'divisible_by_4_not_100', [2428], 'GA_ADAPTIVE'),
    ('is_leap_year', 'not_leap_year', [242], 'GA_ADAPTIVE'),
    ('list_pattern', 'sorted_unique', [[8, 9]], 'GA_ADAPTIVE'),
    ('list_pattern', 'sorted_with_duplicates', [[7, 7]], 'GA_ADAPTIVE'),
    ('list_pattern', 'too_short', [[]], 'GA_ADAPTIVE'),
    ('list_pattern', 'unsorted_unique', [[7, 4, -7]], 'GA_ADAPTIVE'),
    ('list_pattern', 'unsorted_with_duplicates', [[-6, 7, 7, -6, -8, -10]], 'GA_ADAPTIVE'),
    ('list_score', 'empty', [[]], 'GA_ADAPTIVE'),
    ('list_score', 'high', [[16]], 'GA_ADAPTIVE'),
    ('list_score', 'low', [[-8, -6, -2, 5]], 'GA_ADAPTIVE'),
    ('list_score', 'medium', [[8, 5, -1]], 'GA_ADAPTIVE'),
    ('loan_eligibility', 'approve', [58, 65708, True], 'GA_ADAPTIVE'),
    ('loan_eligibility', 'reject_low_income', [22, 6479, True], 'GA_ADAPTIVE'),
    ('loan_eligibility', 'reject_underage', [13, 17788, False], 'GA_ADAPTIVE'),
    ('loan_eligibility', 'review', [26, 44398, False], 'GA_ADAPTIVE'),
    ('max_of_three', 'a_is_max', [72, 70, 26], 'GA_ADAPTIVE'),
    ('max_of_three', 'b_is_max', [-6, 71, -24], 'GA_ADAPTIVE'),
    ('max_of_three', 'c_is_max', [33, -34, 96], 'GA_ADAPTIVE'),
    ('number_kind', 'even', [72], 'GA_ADAPTIVE'),
    ('number_kind', 'odd', [21], 'GA_ADAPTIVE'),
    ('number_kind', 'zero', [0], 'GA_ADAPTIVE'),
    ('password_strength', 'medium', ['3yKs3y'], 'GA_ADAPTIVE'),
    ('password_strength', 'strong', ['8A3z5wlCWNGP1SY'], 'GA_ADAPTIVE'),
    ('password_strength', 'weak_no_digit_upper', ['vkntov'], 'GA_ADAPTIVE'),
    ('password_strength', 'weak_short', ['QR'], 'GA_ADAPTIVE'),
    ('sign_type', 'negative', [-88], 'GA_ADAPTIVE'),
    ('sign_type', 'positive', [21], 'GA_ADAPTIVE'),
    ('sign_type', 'zero', [0], 'GA_ADAPTIVE'),
    ('string_category', 'empty', [''], 'GA_ADAPTIVE'),
    ('string_category', 'long_non_palindrome', ['AazrBjoGnqz'], 'GA_ADAPTIVE'),
    ('string_category', 'long_palindrome', ['yT1Ty'], 'GA_ADAPTIVE'),
    ('string_category', 'other', ['Cry'], 'GA_ADAPTIVE'),
    ('string_category', 'short_palindrome', ['0'], 'GA_ADAPTIVE'),
    ('triangle_type', 'equilateral', [73, 73, 73], 'GA_ADAPTIVE'),
    ('triangle_type', 'invalid_side', [-4, 98, 57], 'GA_ADAPTIVE'),
    ('triangle_type', 'isosceles', [26, 17, 26], 'GA_ADAPTIVE'),
    ('triangle_type', 'not_triangle', [46, 83, 30], 'GA_ADAPTIVE'),
    ('triangle_type', 'scalene', [80, 93, 34], 'GA_ADAPTIVE'),
]

@pytest.mark.parametrize(
    'function_name, target, chromosome, method_used',
    TEST_CASES,
)
def test_llm_generated_input_covers_target(function_name, target, chromosome, method_used):
    target_function = FUNCTIONS[function_name]
    output = target_function(*chromosome)
    assert output == target
    assert validate_branch(function_name, chromosome, target)
    assert get_reached_branch(function_name, chromosome) == target
